CREATE VIEW actors_per_movie AS
select f.title as film_title, c.name as category,
count(fa.actor_id) AS total_actors
from film as f
join film_category as fc ON f.film_id = fc.film_id
join category as c ON fc.category_id = c.category_id
join film_actor as fa ON f.film_id = fa.film_id
group by f.title, c.name;


+-----------------------------+-------------+--------------+
| film_title                  | category    | total_actors |
+-----------------------------+-------------+--------------+
| AMADEUS HOLY                | Action      |            6 |
| AMERICAN CIRCUS             | Action      |            5 |
| ANTITRUST TOMATOES          | Action      |            7 |
| ARK RIDGEMONT               | Action      |            3 |
| BAREFOOT MANCHURIAN         | Action      |            8 |
| BERETS AGENT                | Action      |           10 |
| BRIDE INTRIGUE              | Action      |            1 |
| BULL SHAWSHANK              | Action      |            8 |
| CADDYSHACK JEDI             | Action      |            7 |
| CAMPUS REMEMBER             | Action      |            3 |
| CASUALTIES ENCINO           | Action      |            5 |
| CELEBRITY HORN              | Action      |            4 |
| CLUELESS BUCKET             | Action      |            8 |
| CROW GREASE                 | Action      |           10 |
| DANCES NONE                 | Action      |            5 |
| DARKO DORADO                | Action      |            4 |
| DARN FORRESTER              | Action      |            9 |
| DEVIL DESIRE                | Action      |            5 |
| DRAGON SQUAD                | Action      |            8 |
| DREAM PICKUP                | Action      |            4 |
| DRIFTER COMMANDMENTS        | Action      |            7 |
| EASY GLADIATOR              | Action      |            3 |
| ENTRAPMENT SATISFACTION     | Action      |            4 |
| EXCITEMENT EVE              | Action      |            8 |
| FANTASY TROOPERS            | Action      |            9 |
| FIREHOUSE VIETNAM           | Action      |            5 |
| FOOL MOCKINGBIRD            | Action      |            2 |
| FORREST SONS                | Action      |            5 |
| GLASS DYING                 | Action      |            4 |
| GOSFORD DONNIE              | Action      |            3 |
| GRAIL FRANKENSTEIN          | Action      |            5 |
| HANDICAP BOONDOCK           | Action      |            7 |
| HILLS NEIGHBORS             | Action      |            6 |
| KISSING DOLLS               | Action      |            3 |
| LAWRENCE LOVE               | Action      |            2 |
| LORD ARIZONA                | Action      |            6 |
| LUST LOCK                   | Action      |            7 |
| MAGNOLIA FORRESTER          | Action      |            7 |
| MIDNIGHT WESTWARD           | Action      |            9 |
| MINDS TRUMAN                | Action      |            6 |
| MOCKINGBIRD HOLLYWOOD       | Action      |            3 |
| MONTEZUMA COMMAND           | Action      |            2 |
| PARK CITIZEN                | Action      |            6 |
| PATRIOT ROMAN               | Action      |            4 |
| PRIMARY GLASS               | Action      |            7 |
| QUEST MUSSOLINI             | Action      |            5 |
| REAR TRADING                | Action      |            8 |
| RINGS HEARTBREAKERS         | Action      |           11 |
| RUGRATS SHAKESPEARE         | Action      |            6 |
| SHRUNK DIVINE               | Action      |            4 |
| SIDE ARK                    | Action      |            6 |
| SKY MIRACLE                 | Action      |           12 |
| SOUTH WAIT                  | Action      |            2 |
| SPEAKEASY DATE              | Action      |            3 |
| STAGECOACH ARMAGEDDON       | Action      |            6 |
| STORY SIDE                  | Action      |            5 |
| SUSPECTS QUILLS             | Action      |            8 |
| TRIP NEWTON                 | Action      |            4 |
| TRUMAN CRAZY                | Action      |            6 |
| UPRISING UPTOWN             | Action      |            5 |
| WATERFRONT DELIVERANCE      | Action      |            6 |
| WEREWOLF LOLA               | Action      |            7 |
| WOMEN DORADO                | Action      |            5 |
| WORST BANGER                | Action      |            4 |
| ALTER VICTORY               | Animation   |            4 |
| ANACONDA CONFESSIONS        | Animation   |            5 |
| ARGONAUTS TOWN              | Animation   |            5 |
| BIKINI BORROWERS            | Animation   |            2 |
| BLACKOUT PRIVATE            | Animation   |            5 |
| BORROWERS BEDAZZLED         | Animation   |            7 |
| CANYON STOCK                | Animation   |            6 |
| CAROL TEXAS                 | Animation   |            7 |
| CHAMPION FLATLINERS         | Animation   |            4 |
| CLASH FREDDY                | Animation   |            7 |
| CLUB GRAFFITI               | Animation   |            4 |
| CROSSROADS CASUALTIES       | Animation   |            8 |
| DARES PLUTO                 | Animation   |           10 |
| DESIRE ALIEN                | Animation   |            7 |
| DOGMA FAMILY                | Animation   |            7 |
| DONNIE ALLEY                | Animation   |            7 |
| DOORS PRESIDENT             | Animation   |            9 |
| DOUBLE WRATH                | Animation   |            8 |
| DUCK RACER                  | Animation   |            2 |
| EARLY HOME                  | Animation   |            6 |
| FALCON VOLUME               | Animation   |            4 |
| FIGHT JAWBREAKER            | Animation   |            3 |
| FLOATS GARDEN               | Animation   |            5 |
| FLYING HOOK                 | Animation   |            8 |
| FORRESTER COMANCHEROS       | Animation   |            3 |
| GANGS PRIDE                 | Animation   |            4 |
| GHOSTBUSTERS ELF            | Animation   |            1 |
| HARPER DYING                | Animation   |            4 |
| HOOK CHARIOTS               | Animation   |            4 |
| HORN WORKING                | Animation   |            8 |
| INCH JET                    | Animation   |            5 |
| INSECTS STONE               | Animation   |            4 |
| INTENTIONS EMPIRE           | Animation   |            2 |
| ISHTAR ROCKETEER            | Animation   |            4 |
| JUGGLER HARDLY              | Animation   |            9 |
| LAWLESS VISION              | Animation   |            4 |
| LUKE MUMMY                  | Animation   |            9 |
| MASSAGE IMAGE               | Animation   |            9 |
| MENAGERIE RUSHMORE          | Animation   |            2 |
| MIRACLE VIRTUAL             | Animation   |            1 |
| MISSION ZOOLANDER           | Animation   |            5 |
| NASH CHOCOLAT               | Animation   |            7 |
| OSCAR GOLD                  | Animation   |            6 |
| OZ LIAISONS                 | Animation   |           11 |
| PACKER MADIGAN              | Animation   |            1 |
| POND SEATTLE                | Animation   |            3 |
| POTLUCK MIXED               | Animation   |            6 |
| POTTER CONNECTICUT          | Animation   |            7 |
| PRIDE ALAMO                 | Animation   |            4 |
| PUNK DIVORCE                | Animation   |            7 |
| ROOM ROMAN                  | Animation   |            2 |
| SLEEPLESS MONSOON           | Animation   |            4 |
| SNOWMAN ROLLERCOASTER       | Animation   |            3 |
| SONS INTERVIEW              | Animation   |            6 |
| STORM HAPPINESS             | Animation   |            8 |
| SUGAR WONKA                 | Animation   |            5 |
| SUNRISE LEAGUE              | Animation   |            5 |
| TELEMARK HEARTBREAKERS      | Animation   |           11 |
| THEORY MERMAID              | Animation   |            6 |
| THIEF PELICAN               | Animation   |            7 |
| TITANIC BOONDOCK            | Animation   |           12 |
| TRACY CIDER                 | Animation   |            3 |
| TURN STAR                   | Animation   |            3 |
| WAIT CIDER                  | Animation   |            9 |
| WATCH TRACY                 | Animation   |            5 |
| WONKA SEA                   | Animation   |            2 |
| BACKLASH UNDEFEATED         | Children    |            7 |
| BEAR GRACELAND              | Children    |            3 |
| BENEATH RUSH                | Children    |            7 |
| BETRAYED REAR               | Children    |            4 |
| CABIN FLASH                 | Children    |            4 |
| CASPER DRAGONFLY            | Children    |            5 |
| CHRISTMAS MOONSHINE         | Children    |            3 |
| CIRCUS YOUTH                | Children    |            2 |
| CLOCKWORK PARADISE          | Children    |            5 |
| COMANCHEROS ENEMY           | Children    |            5 |
| CROOKED FROGMEN             | Children    |            6 |
| DAUGHTER MADIGAN            | Children    |            4 |
| DOCTOR GRAIL                | Children    |            6 |
| EMPIRE MALKOVICH            | Children    |            9 |
| FARGO GANDHI                | Children    |            5 |
| FOREVER CANDIDATE           | Children    |            1 |
| FULL FLATLINERS             | Children    |            6 |
| FURY MURDER                 | Children    |            4 |
| GHOST GROUNDHOG             | Children    |            5 |
| GIANT TROOPERS              | Children    |            1 |
| GORGEOUS BINGO              | Children    |            7 |
| GRADUATE LORD               | Children    |            2 |
| HALL CASSIDY                | Children    |            5 |
| HEARTBREAKERS BRIGHT        | Children    |            5 |
| HOLLYWOOD ANONYMOUS         | Children    |            6 |
| HOLOCAUST HIGHBALL          | Children    |            5 |
| IDOLS SNATCHERS             | Children    |            8 |
| INVASION CYCLONE            | Children    |            7 |
| JERSEY SASSY                | Children    |            9 |
| JUMPING WRATH               | Children    |            8 |
| LABYRINTH LEAGUE            | Children    |            6 |
| LANGUAGE COWBOY             | Children    |            6 |
| LEGALLY SECRETARY           | Children    |            6 |
| MAGIC MALLRATS              | Children    |            4 |
| MAKER GABLES                | Children    |           11 |
| MICROCOSMOS PARADISE        | Children    |            6 |
| MODEL FISH                  | Children    |            8 |
| MURDER ANTITRUST            | Children    |            8 |
| NOON PAPI                   | Children    |            6 |
| POLISH BROOKLYN             | Children    |           10 |
| ROBBERS JOON                | Children    |            5 |
| SABRINA MIDNIGHT            | Children    |            4 |
| SANTA PARIS                 | Children    |            6 |
| SCARFACE BANG               | Children    |            7 |
| SHEPHERD MIDSUMMER          | Children    |            5 |
| SISTER FREDDY               | Children    |            3 |
| SPLENDOR PATTON             | Children    |           10 |
| STRANGELOVE DESIRE          | Children    |            9 |
| STRANGER STRANGERS          | Children    |            9 |
| SUNDANCE INVASION           | Children    |            7 |
| SWEETHEARTS SUSPECTS        | Children    |            5 |
| TEQUILA PAST                | Children    |            3 |
| TIES HUNGER                 | Children    |            6 |
| TOOTSIE PILOT               | Children    |            5 |
| TWISTED PIRATES             | Children    |            3 |
| UPTOWN YOUNG                | Children    |            7 |
| WALLS ARTIST                | Children    |            5 |
| WARLOCK WEREWOLF            | Children    |            6 |
| WRONG BEHAVIOR              | Children    |            9 |
| ZOOLANDER FICTION           | Children    |            5 |
| ALICE FANTASIA              | Classics    |            4 |
| ARIZONA BANG                | Classics    |            4 |
| BEAST HUNCHBACK             | Classics    |            5 |
| BOUND CHEAPER               | Classics    |            2 |
| CANDIDATE PERDITION         | Classics    |            4 |
| CENTER DINOSAUR             | Classics    |            4 |
| COLOR PHILADELPHIA          | Classics    |            7 |
| CONSPIRACY SPIRIT           | Classics    |            4 |
| CORE SUIT                   | Classics    |            4 |
| CREEPERS KANE               | Classics    |            6 |
| CRUELTY UNFORGIVEN          | Classics    |            2 |
| DETECTIVE VISION            | Classics    |            3 |
| DRACULA CRYSTAL             | Classics    |           13 |
| DYNAMITE TARZAN             | Classics    |            5 |
| EXTRAORDINARY CONQUERER     | Classics    |            7 |
| FROST HEAD                  | Classics    |            7 |
| GALAXY SWEETHEARTS          | Classics    |            3 |
| GILBERT PELICAN             | Classics    |            4 |
| GILMORE BOILED              | Classics    |            6 |
| HOLY TADPOLE                | Classics    |            3 |
| HOPE TOOTSIE                | Classics    |            4 |
| HYDE DOCTOR                 | Classics    |            6 |
| IRON MOON                   | Classics    |            8 |
| ISLAND EXORCIST             | Classics    |            3 |
| JEEPERS WEDDING             | Classics    |            6 |
| JEOPARDY ENCINO             | Classics    |            5 |
| JERK PAYCHECK               | Classics    |            8 |
| JINGLE SAGEBRUSH            | Classics    |            2 |
| LEAGUE HELLFIGHTERS         | Classics    |            6 |
| LIGHTS DEER                 | Classics    |            2 |
| LOATHING LEGALLY            | Classics    |            5 |
| LOVELY JINGLE               | Classics    |            6 |
| LOVER TRUMAN                | Classics    |            7 |
| MAGNIFICENT CHITTY          | Classics    |            7 |
| MALKOVICH PET               | Classics    |            7 |
| MILLION ACE                 | Classics    |            5 |
| MUSKETEERS WAIT             | Classics    |            1 |
| OCTOBER SUBMARINE           | Classics    |            5 |
| PAJAMA JAWBREAKER           | Classics    |            5 |
| PATIENT SISTER              | Classics    |            4 |
| PREJUDICE OLEANDER          | Classics    |           10 |
| REQUIEM TYCOON              | Classics    |            8 |
| RIGHT CRANES                | Classics    |            7 |
| ROOTS REMEMBER              | Classics    |           10 |
| SLING LUKE                  | Classics    |            3 |
| SNATCHERS MONTEZUMA         | Classics    |            9 |
| SPIKING ELEMENT             | Classics    |            6 |
| STEEL SANTA                 | Classics    |            3 |
| SUMMER SCARFACE             | Classics    |            8 |
| TADPOLE PARK                | Classics    |            8 |
| TIMBERLAND SKY              | Classics    |            4 |
| TOMORROW HUSTLER            | Classics    |            6 |
| TOWERS HURRICANE            | Classics    |            4 |
| VOLUME HOUSE                | Classics    |            5 |
| VOYAGE LEGALLY              | Classics    |            5 |
| WASTELAND DIVINE            | Classics    |            6 |
| WESTWARD SEABISCUIT         | Classics    |            6 |
| AIRPLANE SIERRA             | Comedy      |            5 |
| ANTHEM LUKE                 | Comedy      |            2 |
| BRINGING HYSTERICAL         | Comedy      |            2 |
| CAPER MOTIONS               | Comedy      |            7 |
| CAT CONEHEADS               | Comedy      |            4 |
| CLOSER BANG                 | Comedy      |            6 |
| CONNECTION MICROCOSMOS      | Comedy      |            7 |
| CONTROL ANTHEM              | Comedy      |            3 |
| CRAZY HOME                  | Comedy      |           13 |
| DADDY PITTSBURGH            | Comedy      |            5 |
| DOOM DANCING                | Comedy      |            8 |
| DOWNHILL ENOUGH             | Comedy      |            4 |
| DYING MAKER                 | Comedy      |            2 |
| ELEMENT FREDDY              | Comedy      |            4 |
| FERRIS MOTHER               | Comedy      |            1 |
| FIREBALL PHILADELPHIA       | Comedy      |            5 |
| FLINTSTONES HAPPINESS       | Comedy      |            4 |
| FRANKENSTEIN STRANGER       | Comedy      |            2 |
| FREEDOM CLEOPATRA           | Comedy      |            5 |
| GOLD RIVER                  | Comedy      |            2 |
| GROUNDHOG UNCUT             | Comedy      |            7 |
| GUNFIGHT MOON               | Comedy      |            4 |
| HATE HANDICAP               | Comedy      |            3 |
| HEAVEN FREEDOM              | Comedy      |           10 |
| HEDWIG ALTER                | Comedy      |            4 |
| HURRICANE AFFAIR            | Comedy      |            3 |
| HUSTLER PARTY               | Comedy      |            4 |
| JAWS HARRY                  | Comedy      |            5 |
| KNOCK WARLOCK               | Comedy      |            6 |
| LIFE TWISTED                | Comedy      |            8 |
| LION UNCUT                  | Comedy      |            3 |
| LONELY ELEPHANT             | Comedy      |           12 |
| MALLRATS UNITED             | Comedy      |            5 |
| MEMENTO ZOOLANDER           | Comedy      |            6 |
| MULAN MOON                  | Comedy      |            5 |
| MYSTIC TRUMAN               | Comedy      |            4 |
| OPERATION OPERATION         | Comedy      |            3 |
| PARADISE SABRINA            | Comedy      |            4 |
| PARTY KNOCK                 | Comedy      |            2 |
| PERFECT GROOVE              | Comedy      |            6 |
| PINOCCHIO SIMON             | Comedy      |           11 |
| PURE RUNNER                 | Comedy      |            2 |
| RUSHMORE MERMAID            | Comedy      |            7 |
| SADDLE ANTITRUST            | Comedy      |            3 |
| SATURN NAME                 | Comedy      |            2 |
| SEARCHERS WAIT              | Comedy      |            4 |
| SNATCH SLIPPER              | Comedy      |            3 |
| STAGE WORLD                 | Comedy      |            2 |
| STRICTLY SCARFACE           | Comedy      |            4 |
| SUBMARINE BED               | Comedy      |           11 |
| SWEDEN SHINING              | Comedy      |            5 |
| TRAINSPOTTING STRANGERS     | Comedy      |            4 |
| TRAMP OTHERS                | Comedy      |            6 |
| VALLEY PACKER               | Comedy      |            4 |
| VELVET TERMINATOR           | Comedy      |            9 |
| VERTIGO NORTHWEST           | Comedy      |            4 |
| WISDOM WORKER               | Comedy      |            7 |
| ZORRO ARK                   | Comedy      |            3 |
| ACADEMY DINOSAUR            | Documentary |           10 |
| ADAPTATION HOLES            | Documentary |            5 |
| ARMY FLINTSTONES            | Documentary |            7 |
| BEACH HEARTBREAKERS         | Documentary |            7 |
| BED HIGHBALL                | Documentary |            5 |
| BILL OTHERS                 | Documentary |            6 |
| BONNIE HOLOCAUST            | Documentary |            9 |
| BROTHERHOOD BLANKET         | Documentary |            5 |
| CAUSE DATE                  | Documentary |            6 |
| CHICKEN HELLFIGHTERS        | Documentary |            2 |
| CIDER DESIRE                | Documentary |            5 |
| CLERKS ANGELS               | Documentary |            4 |
| COAST RAINBOW               | Documentary |           10 |
| CUPBOARD SINNERS            | Documentary |            8 |
| DANCING FEVER               | Documentary |            6 |
| DEEP CRUSADE                | Documentary |            7 |
| DELIVERANCE MULHOLLAND      | Documentary |            3 |
| DOZEN LION                  | Documentary |            6 |
| DUFFEL APOCALYPSE           | Documentary |            3 |
| EGG IGBY                    | Documentary |            5 |
| EXPENDABLE STALLION         | Documentary |            4 |
| FRENCH HOLIDAY              | Documentary |            7 |
| HALLOWEEN NUTS              | Documentary |            7 |
| HARDLY ROBBERS              | Documentary |            3 |
| HAWK CHILL                  | Documentary |            7 |
| HEAVYWEIGHTS BEAST          | Documentary |            5 |
| HOMEWARD CIDER              | Documentary |            7 |
| HUNTER ALTER                | Documentary |            4 |
| INDEPENDENCE HOTEL          | Documentary |            9 |
| INTOLERABLE INTENTIONS      | Documentary |            6 |
| KILL BROTHERHOOD            | Documentary |            5 |
| MADISON TRAP                | Documentary |            5 |
| MAJESTIC FLOATS             | Documentary |            5 |
| METAL ARMAGEDDON            | Documentary |            8 |
| MIDSUMMER GROUNDHOG         | Documentary |            2 |
| MIGHTY LUCK                 | Documentary |            8 |
| MOD SECRETARY               | Documentary |            6 |
| MODERN DORADO               | Documentary |            5 |
| NATIONAL STORY              | Documentary |            7 |
| NEWSIES STORY               | Documentary |            8 |
| NORTH TEQUILA               | Documentary |            5 |
| NOTORIOUS REUNION           | Documentary |            2 |
| PACIFIC AMISTAD             | Documentary |            8 |
| PELICAN COMFORTS            | Documentary |            5 |
| POCUS PULP                  | Documentary |            5 |
| PRINCESS GIANT              | Documentary |            5 |
| QUILLS BULL                 | Documentary |            4 |
| RAIDERS ANTITRUST           | Documentary |            6 |
| RAINBOW SHOCK               | Documentary |            6 |
| ROAD ROXANNE                | Documentary |            8 |
| SAGEBRUSH CLUELESS          | Documentary |            7 |
| SECRET GROUNDHOG            | Documentary |            3 |
| SHIP WONDERLAND             | Documentary |            8 |
| SHOW LORD                   | Documentary |            2 |
| SMOKING BARBARELLA          | Documentary |            6 |
| SPOILERS HELLFIGHTERS       | Documentary |            7 |
| STREAK RIDGEMONT            | Documentary |            3 |
| THIN SAGEBRUSH              | Documentary |            2 |
| UNITED PILOT                | Documentary |            6 |
| UNTOUCHABLES SUNRISE        | Documentary |            5 |
| VILLAIN DESPERATE           | Documentary |            2 |
| VIRGINIAN PLUTO             | Documentary |            8 |
| WAGON JAWS                  | Documentary |            6 |
| WARS PLUTO                  | Documentary |            4 |
| WEDDING APOLLO              | Documentary |           10 |
| WIFE TURN                   | Documentary |            6 |
| WRATH MILE                  | Documentary |            4 |
| YOUNG LANGUAGE              | Documentary |            5 |
| APOLLO TEEN                 | Drama       |            8 |
| BEAUTY GREASE               | Drama       |            5 |
| BEETHOVEN EXORCIST          | Drama       |            6 |
| BLADE POLISH                | Drama       |            5 |
| BRIGHT ENCOUNTERS           | Drama       |            4 |
| BUNCH MINDS                 | Drama       |            8 |
| CHILL LUCK                  | Drama       |            5 |
| CHITTY LOCK                 | Drama       |           13 |
| CONEHEADS SMOOCHY           | Drama       |            9 |
| CONFESSIONS MAGUIRE         | Drama       |            4 |
| CONQUERER NUTS              | Drama       |            6 |
| CRAFT OUTFIELD              | Drama       |            6 |
| DALMATIONS SWEDEN           | Drama       |            6 |
| DARKNESS WAR                | Drama       |            2 |
| DECEIVER BETRAYED           | Drama       |            4 |
| DESTINATION JERK            | Drama       |            3 |
| DIARY PANIC                 | Drama       |            4 |
| EDGE KISSING                | Drama       |            3 |
| ENCOUNTERS CURTAIN          | Drama       |            4 |
| GOLDFINGER SENSIBILITY      | Drama       |            4 |
| GONE TROUBLE                | Drama       |            5 |
| GREEDY ROOTS                | Drama       |            8 |
| HANGING DEEP                | Drama       |            7 |
| HAROLD FRENCH               | Drama       |            7 |
| HARRY IDAHO                 | Drama       |            6 |
| HOBBIT ALIEN                | Drama       |            8 |
| HUNCHBACK IMPOSSIBLE        | Drama       |            2 |
| JACKET FRISCO               | Drama       |           10 |
| KWAI HOMEWARD               | Drama       |            5 |
| LEBOWSKI SOLDIERS           | Drama       |            3 |
| LIES TREATMENT              | Drama       |            7 |
| LUCK OPUS                   | Drama       |            6 |
| MOB DUFFEL                  | Drama       |            6 |
| NECKLACE OUTBREAK           | Drama       |            8 |
| NOTTING SPEAKEASY           | Drama       |            2 |
| ORIENT CLOSER               | Drama       |            4 |
| PATHS CONTROL               | Drama       |            5 |
| PAYCHECK WAIT               | Drama       |            3 |
| PITY BOUND                  | Drama       |            5 |
| QUEEN LUKE                  | Drama       |            6 |
| RACER EGG                   | Drama       |            6 |
| REUNION WITCHES             | Drama       |            7 |
| ROCKY WAR                   | Drama       |            3 |
| SAINTS BRIDE                | Drama       |           10 |
| SAVANNAH TOWN               | Drama       |            6 |
| SCORPION APOLLO             | Drama       |            8 |
| SEA VIRGIN                  | Drama       |            8 |
| SEATTLE EXPECATIONS         | Drama       |            6 |
| SHOOTIST SUPERFLY           | Drama       |            3 |
| SOMETHING DUCK              | Drama       |            3 |
| SPICE SORORITY              | Drama       |           11 |
| TENENBAUMS COMMAND          | Drama       |            5 |
| TORQUE BOUND                | Drama       |            5 |
| TRANSLATION SUMMER          | Drama       |            3 |
| TREATMENT JEKYLL            | Drama       |            5 |
| UNFAITHFUL KILL             | Drama       |            8 |
| VIETNAM SMOOCHY             | Drama       |            2 |
| VIRGIN DAISY                | Drama       |            8 |
| WARDROBE PHANTOM            | Drama       |            8 |
| WEST LION                   | Drama       |            9 |
| WITCHES PANIC               | Drama       |            4 |
| AFRICAN EGG                 | Family      |            5 |
| APACHE DIVINE               | Family      |            4 |
| ATLANTIS CAUSE              | Family      |            9 |
| BAKED CLEOPATRA             | Family      |            1 |
| BANG KWAI                   | Family      |            7 |
| BEDAZZLED MARRIED           | Family      |            7 |
| BILKO ANONYMOUS             | Family      |            3 |
| BLANKET BEVERLY             | Family      |            4 |
| BLOOD ARGONAUTS             | Family      |            4 |
| BLUES INSTINCT              | Family      |            4 |
| BRAVEHEART HUMAN            | Family      |            4 |
| CHASING FIGHT               | Family      |            5 |
| CHISUM BEHAVIOR             | Family      |            4 |
| CHOCOLAT HARRY              | Family      |            5 |
| CONFUSED CANDLES            | Family      |            6 |
| CONVERSATION DOWNHILL       | Family      |            3 |
| DATE SPEED                  | Family      |            4 |
| DINOSAUR SECRETARY          | Family      |            6 |
| DUMBO LUST                  | Family      |            9 |
| EARRING INSTINCT            | Family      |            5 |
| EFFECT GLADIATOR            | Family      |            7 |
| FEUD FROGMEN                | Family      |            4 |
| FINDING ANACONDA            | Family      |            5 |
| GABLES METROPOLIS           | Family      |            8 |
| GANDHI KWAI                 | Family      |            8 |
| GLADIATOR WESTWARD          | Family      |            6 |
| GREASE YOUTH                | Family      |            3 |
| HALF OUTFIELD               | Family      |            6 |
| HOCUS FRIDA                 | Family      |            3 |
| HOMICIDE PEACH              | Family      |            8 |
| HOUSE DYNAMITE              | Family      |            9 |
| HUNTING MUSKETEERS          | Family      |            5 |
| INDIAN LOVE                 | Family      |           10 |
| JASON TRAP                  | Family      |            5 |
| JEDI BENEATH                | Family      |            4 |
| KILLER INNOCENT             | Family      |            5 |
| KING EVOLUTION              | Family      |            6 |
| LOLITA WORLD                | Family      |            1 |
| LOUISIANA HARRY             | Family      |            3 |
| MAGUIRE APACHE              | Family      |            4 |
| MANCHURIAN CURTAIN          | Family      |            2 |
| MOVIE SHAKESPEARE           | Family      |            8 |
| MUSIC BOONDOCK              | Family      |            3 |
| NATURAL STOCK               | Family      |            4 |
| NETWORK PEAK                | Family      |            3 |
| ODDS BOOGIE                 | Family      |            5 |
| OPPOSITE NECKLACE           | Family      |            6 |
| PILOT HOOSIERS              | Family      |            7 |
| PITTSBURGH HUNCHBACK        | Family      |            5 |
| PRESIDENT BANG              | Family      |            5 |
| PRIX UNDEFEATED             | Family      |            7 |
| RAGE GAMES                  | Family      |            7 |
| RANGE MOONWALKER            | Family      |            4 |
| REMEMBER DIARY              | Family      |            4 |
| RESURRECTION SILVERADO      | Family      |            5 |
| ROBBERY BRIGHT              | Family      |            2 |
| RUSH GOODFELLAS             | Family      |            5 |
| SECRETS PARADISE            | Family      |            6 |
| SENSIBILITY REAR            | Family      |            6 |
| SIEGE MADRE                 | Family      |            7 |
| SLUMS DUCK                  | Family      |            3 |
| SOUP WISDOM                 | Family      |            2 |
| SPARTACUS CHEAPER           | Family      |            3 |
| SPINAL ROCKY                | Family      |            8 |
| SPLASH GUMP                 | Family      |           10 |
| SUNSET RACER                | Family      |            3 |
| SUPER WYOMING               | Family      |            3 |
| VIRTUAL SPOILERS            | Family      |            3 |
| WILLOW TRACY                | Family      |            2 |
| AGENT TRUMAN                | Foreign     |            7 |
| ALAMO VIDEOTAPE             | Foreign     |            4 |
| ALIEN CENTER                | Foreign     |            6 |
| ALLEY EVOLUTION             | Foreign     |            5 |
| BABY HALL                   | Foreign     |            8 |
| BALLROOM MOCKINGBIRD        | Foreign     |            7 |
| BROOKLYN DESERT             | Foreign     |            5 |
| BUGSY SONG                  | Foreign     |            2 |
| CALENDAR GUNFIGHT           | Foreign     |            8 |
| CATCH AMISTAD               | Foreign     |            5 |
| CHOCOLATE DUCK              | Foreign     |            7 |
| COMMAND DARLING             | Foreign     |            8 |
| COWBOY DOOM                 | Foreign     |            5 |
| CROSSING DIVORCE            | Foreign     |            2 |
| CRYSTAL BREAKING            | Foreign     |            5 |
| CYCLONE FAMILY              | Foreign     |            3 |
| DANGEROUS UPTOWN            | Foreign     |            8 |
| DOUBTFIRE LABYRINTH         | Foreign     |            5 |
| EVERYONE CRAFT              | Foreign     |            5 |
| FICTION CHRISTMAS           | Foreign     |            8 |
| FRIDA SLIPPER               | Foreign     |            5 |
| GENTLEMEN STAGE             | Foreign     |            8 |
| GRAPES FURY                 | Foreign     |            5 |
| GREEK EVERYONE              | Foreign     |            4 |
| HAPPINESS UNITED            | Foreign     |            5 |
| HELLFIGHTERS SIERRA         | Foreign     |           12 |
| HIGHBALL POTTER             | Foreign     |            5 |
| HOLIDAY GAMES               | Foreign     |            6 |
| HOOSIERS BIRDCAGE           | Foreign     |           10 |
| HOTEL HAPPINESS             | Foreign     |            4 |
| HUNGER ROOF                 | Foreign     |            1 |
| ILLUSION AMELIE             | Foreign     |            7 |
| IMPOSSIBLE PREJUDICE        | Foreign     |            3 |
| INFORMER DOUBLE             | Foreign     |            3 |
| INNOCENT USUAL              | Foreign     |            3 |
| INTRIGUE WORST              | Foreign     |            7 |
| JET NEIGHBORS               | Foreign     |            6 |
| KANE EXORCIST               | Foreign     |            5 |
| KISS GLORY                  | Foreign     |            7 |
| LOSE INCH                   | Foreign     |            4 |
| LOST BIRD                   | Foreign     |            3 |
| MADNESS ATTACKS             | Foreign     |            7 |
| MATRIX SNOWMAN              | Foreign     |            3 |
| MAUDE MOD                   | Foreign     |            6 |
| MEET CHOCOLATE              | Foreign     |            6 |
| MIXED DOORS                 | Foreign     |            6 |
| MOON BUNCH                  | Foreign     |            1 |
| MULHOLLAND BEAST            | Foreign     |            6 |
| MUPPET MILE                 | Foreign     |            8 |
| NEWTON LABYRINTH            | Foreign     |            4 |
| OPUS ICE                    | Foreign     |            4 |
| ORANGE GRAPES               | Foreign     |            5 |
| PAST SUICIDES               | Foreign     |            6 |
| PEARL DESTINY               | Foreign     |            4 |
| PET HAUNTING                | Foreign     |            7 |
| POLLOCK DELIVERANCE         | Foreign     |            6 |
| PURPLE MOVIE                | Foreign     |            8 |
| RESERVOIR ADAPTATION        | Foreign     |            8 |
| ROCKETEER MOTHER            | Foreign     |            7 |
| SCHOOL JACKET               | Foreign     |            8 |
| SCISSORHANDS SLUMS          | Foreign     |            5 |
| SHOCK CABIN                 | Foreign     |            1 |
| SHREK LICENSE               | Foreign     |            3 |
| SORORITY QUEEN              | Foreign     |            4 |
| STEPMOM DREAM               | Foreign     |            4 |
| TOWN ARK                    | Foreign     |            4 |
| TRAP GUYS                   | Foreign     |            7 |
| USUAL UNTOUCHABLES          | Foreign     |            5 |
| VISION TORQUE               | Foreign     |            5 |
| WAR NOTTING                 | Foreign     |            9 |
| WASH HEAVENLY               | Foreign     |            5 |
| WHALE BIKINI                | Foreign     |            5 |
| WONDERFUL DROP              | Foreign     |            4 |
| AUTUMN CROW                 | Games       |            3 |
| BULWORTH COMMANDMENTS       | Games       |            4 |
| CANDLES GRAPES              | Games       |            7 |
| CHICAGO NORTH               | Games       |            8 |
| CREATURES SHAKESPEARE       | Games       |            3 |
| CURTAIN VIDEOTAPE           | Games       |            3 |
| DARLING BREAKING            | Games       |            2 |
| DAWN POND                   | Games       |            6 |
| DAZED PUNK                  | Games       |            6 |
| DETAILS PACKER              | Games       |            2 |
| DIRTY ACE                   | Games       |            5 |
| DIVINE RESURRECTION         | Games       |            5 |
| DWARFS ALTER                | Games       |            1 |
| ENCINO ELF                  | Games       |            6 |
| FANTASIA PARK               | Games       |            3 |
| FEATHERS METAL              | Games       |            9 |
| FEVER EMPIRE                | Games       |            3 |
| FIRE WOLVES                 | Games       |            5 |
| FORWARD TEMPLE              | Games       |            3 |
| GATHERING CALENDAR          | Games       |            3 |
| GLORY TRACY                 | Games       |            6 |
| GRINCH MASSAGE              | Games       |            6 |
| GRIT CLOCKWORK              | Games       |            3 |
| GUN BONNIE                  | Games       |            5 |
| HAUNTING PIANIST            | Games       |            5 |
| HEAD STRANGER               | Games       |            2 |
| HUMAN GRAFFITI              | Games       |            4 |
| ICE CROSSING                | Games       |            6 |
| JERICHO MULAN               | Games       |            4 |
| LADYBUGS ARMAGEDDON         | Games       |            4 |
| LAMBS CINCINATTI            | Games       |           15 |
| MADRE GABLES                | Games       |            4 |
| MALTESE HOPE                | Games       |            1 |
| MARS ROMAN                  | Games       |            7 |
| MASSACRE USUAL              | Games       |            3 |
| MONSOON CAUSE               | Games       |            5 |
| MOONSHINE CABIN             | Games       |            5 |
| MOONWALKER FOOL             | Games       |            7 |
| NAME DETECTIVE              | Games       |            3 |
| NIGHTMARE CHILL             | Games       |            2 |
| OUTBREAK DIVINE             | Games       |            5 |
| PANKY SUBMARINE             | Games       |            8 |
| PIZZA JUMANJI               | Games       |            5 |
| PRIVATE DROP                | Games       |            5 |
| PSYCHO SHRUNK               | Games       |            1 |
| ROOF CHAMPION               | Games       |            5 |
| ROUGE SQUAD                 | Games       |            4 |
| ROXANNE REBEL               | Games       |            5 |
| SASSY PACKER                | Games       |            3 |
| SEVEN SWARM                 | Games       |            7 |
| SLEUTH ORIENT               | Games       |            7 |
| SPY MILE                    | Games       |            8 |
| STAMPEDE DISTURBING         | Games       |            6 |
| STATE WASTELAND             | Games       |            7 |
| SUIT WALLS                  | Games       |            5 |
| TYCOON GATHERING            | Games       |            6 |
| VANILLA DAY                 | Games       |            2 |
| VIDEOTAPE ARSENIC           | Games       |            5 |
| VOLCANO TEXAS               | Games       |            5 |
| WANDA CHAMBER               | Games       |            7 |
| WIND PHANTOM                | Games       |            3 |
| ACE GOLDFINGER              | Horror      |            4 |
| AFFAIR PREJUDICE            | Horror      |            5 |
| AIRPORT POLLOCK             | Horror      |            4 |
| ALABAMA DEVIL               | Horror      |            9 |
| ALI FOREVER                 | Horror      |            5 |
| ANALYZE HOOSIERS            | Horror      |            5 |
| ANYTHING SAVANNAH           | Horror      |            3 |
| ARABIA DOGMA                | Horror      |           12 |
| ARACHNOPHOBIA ROLLERCOASTER | Horror      |            8 |
| BEHAVIOR RUNAWAY            | Horror      |            5 |
| BOWFINGER GABLES            | Horror      |            5 |
| CARRIE BUNCH                | Horror      |            7 |
| COMMANDMENTS EXPRESS        | Horror      |            4 |
| DESERT POSEIDON             | Horror      |            5 |
| DRUMS DYNAMITE              | Horror      |            7 |
| EGYPT TENENBAUMS            | Horror      |            5 |
| ELEPHANT TROJAN             | Horror      |            5 |
| FAMILY SWEET                | Horror      |            9 |
| FIDELITY DEVIL              | Horror      |            4 |
| FREDDY STORM                | Horror      |            3 |
| GASLIGHT CRUSADE            | Horror      |            5 |
| HIGH ENCINO                 | Horror      |            7 |
| JAPANESE RUN                | Horror      |            9 |
| KARATE MOON                 | Horror      |            8 |
| KENTUCKIAN GIANT            | Horror      |            4 |
| LADY STAGE                  | Horror      |            8 |
| LOLA AGENT                  | Horror      |            6 |
| LOVE SUICIDES               | Horror      |            4 |
| MONTEREY LABYRINTH          | Horror      |            6 |
| MOTIONS DETAILS             | Horror      |            8 |
| PANIC CLUB                  | Horror      |            3 |
| PARIS WEEKEND               | Horror      |            6 |
| PATTON INTERVIEW            | Horror      |            9 |
| PULP BEVERLY                | Horror      |            7 |
| REAP UNFAITHFUL             | Horror      |            4 |
| REEF SALUTE                 | Horror      |            4 |
| ROCK INSTINCT               | Horror      |            8 |
| ROLLERCOASTER BRINGING      | Horror      |            3 |
| RULES HUMAN                 | Horror      |            5 |
| SIMON NORTH                 | Horror      |            3 |
| SINNERS ATLANTIS            | Horror      |            4 |
| SLEEPING SUSPECTS           | Horror      |            4 |
| SPIRIT FLINTSTONES          | Horror      |           11 |
| STRANGERS GRAFFITI          | Horror      |            5 |
| STREETCAR INTENTIONS        | Horror      |            7 |
| SWARM GOLD                  | Horror      |            6 |
| TARZAN VIDEOTAPE            | Horror      |            3 |
| TEMPLE ATTRACTION           | Horror      |            5 |
| TEXAS WATCH                 | Horror      |            6 |
| TRAIN BUNCH                 | Horror      |            4 |
| TREASURE COMMAND            | Horror      |            7 |
| UNDEFEATED DALMATIONS       | Horror      |            3 |
| WATERSHIP FRONTIER          | Horror      |            6 |
| WORLD LEATHERNECKS          | Horror      |            8 |
| YENTL IDAHO                 | Horror      |            1 |
| ZHIVAGO CORE                | Horror      |            6 |
| ALASKA PHANTOM              | Music       |            7 |
| ALONE TRIP                  | Music       |            8 |
| AMELIE HELLFIGHTERS         | Music       |            6 |
| BALLOON HOMEWARD            | Music       |            6 |
| BANGER PINOCCHIO            | Music       |            6 |
| BIRCH ANTITRUST             | Music       |            6 |
| BIRDCAGE CASPER             | Music       |            4 |
| BOOGIE AMELIE               | Music       |            6 |
| CHAMBER ITALIAN             | Music       |            7 |
| CLONES PINOCCHIO            | Music       |            5 |
| CLUE GRAIL                  | Music       |            6 |
| CONFIDENTIAL INTERVIEW      | Music       |            2 |
| DEER VIRGINIAN              | Music       |            3 |
| DORADO NOTTING              | Music       |            4 |
| DRIVING POLISH              | Music       |            7 |
| ELF MURDER                  | Music       |            5 |
| ENEMY ODDS                  | Music       |            4 |
| FREAKY POCUS                | Music       |            5 |
| GO PURPLE                   | Music       |            3 |
| GREATEST NORTH              | Music       |            6 |
| GROSSE WONDERFUL            | Music       |            4 |
| HANOVER GALAXY              | Music       |            7 |
| HEAVENLY GUN                | Music       |            6 |
| HOME PITY                   | Music       |            6 |
| IMPACT ALADDIN              | Music       |            3 |
| INSIDER ARIZONA             | Music       |            9 |
| JAWBREAKER BROOKLYN         | Music       |            5 |
| LEGEND JEDI                 | Music       |            4 |
| LUCKY FLYING                | Music       |           10 |
| MASKED BUBBLE               | Music       |            3 |
| MINORITY KISS               | Music       |            1 |
| MONSTER SPARTACUS           | Music       |            7 |
| OLEANDER CLUE               | Music       |           10 |
| OUTFIELD MASSACRE           | Music       |            4 |
| PERSONAL LADYBUGS           | Music       |            9 |
| REBEL AIRPORT               | Music       |            6 |
| REDS POCUS                  | Music       |            5 |
| ROMAN PUNK                  | Music       |            2 |
| RUNNER MADIGAN              | Music       |            8 |
| SCALAWAG DUCK               | Music       |            5 |
| SILENCE KANE                | Music       |            4 |
| SONG HEDWIG                 | Music       |            5 |
| TAXI KICK                   | Music       |            6 |
| TELEGRAPH VOYAGE            | Music       |            7 |
| TERMINATOR CLUB             | Music       |            2 |
| UNCUT SUICIDES              | Music       |            7 |
| VANISHING ROCKY             | Music       |            5 |
| WIZARD COLDBLOODED          | Music       |            9 |
| WON DARES                   | Music       |            5 |
| WORDS HUNTER                | Music       |            6 |
| YOUTH KICK                  | Music       |            5 |
| AMISTAD MIDSUMMER           | New         |            4 |
| ANGELS LIFE                 | New         |            9 |
| APOCALYPSE FLAMINGOS        | New         |            5 |
| ATTRACTION NEWTON           | New         |            4 |
| BIRDS PERDITION             | New         |            4 |
| BOULEVARD MOB               | New         |            8 |
| BRANNIGAN SUNRISE           | New         |            2 |
| BREAKFAST GOLDFINGER        | New         |            5 |
| BREAKING HOME               | New         |            6 |
| BUTCH PANTHER               | New         |            3 |
| BUTTERFLY CHOCOLAT          | New         |            7 |
| CHAPLIN LICENSE             | New         |            6 |
| CHINATOWN GLADIATOR         | New         |           10 |
| CLEOPATRA DEVIL             | New         |            7 |
| CLYDE THEORY                | New         |            4 |
| DAY UNFAITHFUL              | New         |            5 |
| DESTINY SATURDAY            | New         |            7 |
| DRAGONFLY STRANGERS         | New         |            3 |
| EAGLES PANKY                | New         |            6 |
| EARTH VISION                | New         |            3 |
| ENDING CROWDS               | New         |            5 |
| EVE RESURRECTION            | New         |            6 |
| FATAL HAUNTED               | New         |            6 |
| FLAMINGOS CONNECTICUT       | New         |            9 |
| FLASH WARS                  | New         |            7 |
| FRONTIER CABIN              | New         |            6 |
| GODFATHER DIARY             | New         |            6 |
| HOURS RAGE                  | New         |            6 |
| IDAHO LOVE                  | New         |            6 |
| INTERVIEW LIAISONS          | New         |            5 |
| JEKYLL FROGMEN              | New         |            3 |
| JUMANJI BLADE               | New         |            6 |
| JUNGLE CLOSER               | New         |            6 |
| LOVERBOY ATTACKS            | New         |            9 |
| MAIDEN HOME                 | New         |            8 |
| MANNEQUIN WORST             | New         |            5 |
| MASK PEACH                  | New         |           11 |
| MINE TITANS                 | New         |            2 |
| MONEY HAROLD                | New         |            7 |
| NUTS TIES                   | New         |            2 |
| OKLAHOMA JUMANJI            | New         |            9 |
| PHANTOM GLORY               | New         |            2 |
| PIANIST OUTFIELD            | New         |            5 |
| PLATOON INSTINCT            | New         |            5 |
| PLUTO OLEANDER              | New         |            7 |
| REDEMPTION COMFORTS         | New         |            5 |
| RIDGEMONT SUBMARINE         | New         |            5 |
| RUN PACIFIC                 | New         |            6 |
| RUNAWAY TENENBAUMS          | New         |            3 |
| SALUTE APOLLO               | New         |            4 |
| SAMURAI LION                | New         |            2 |
| SLEEPY JAPANESE             | New         |            6 |
| STING PERSONAL              | New         |            7 |
| STOCK GLASS                 | New         |            7 |
| TROOPERS METAL              | New         |            5 |
| UNBREAKABLE KARATE          | New         |            8 |
| VAMPIRE WHALE               | New         |            5 |
| VANISHED GARDEN             | New         |            2 |
| VARSITY TRIP                | New         |            3 |
| VOICE PEACH                 | New         |            3 |
| WAKE JAWS                   | New         |            5 |
| WILD APOLLO                 | New         |            4 |
| WYOMING STORM               | New         |            6 |
| ANNIE IDENTITY              | Sci-Fi      |            3 |
| ARMAGEDDON LOST             | Sci-Fi      |            7 |
| ATTACKS HATE                | Sci-Fi      |            4 |
| BADMAN DAWN                 | Sci-Fi      |            8 |
| BARBARELLA STREETCAR        | Sci-Fi      |            5 |
| BEVERLY OUTLAW              | Sci-Fi      |            4 |
| BINGO TALENTED              | Sci-Fi      |            5 |
| BLINDNESS GUN               | Sci-Fi      |            3 |
| CAMELOT VACATION            | Sci-Fi      |            2 |
| CHAINSAW UPTOWN             | Sci-Fi      |            2 |
| CHARADE DUFFEL              | Sci-Fi      |            3 |
| CHARIOTS CONSPIRACY         | Sci-Fi      |            2 |
| CHEAPER CLYDE               | Sci-Fi      |            2 |
| CINCINATTI WHISPERER        | Sci-Fi      |            4 |
| CITIZEN SHREK               | Sci-Fi      |            8 |
| COLDBLOODED DARLING         | Sci-Fi      |            4 |
| CONNECTICUT TRAMP           | Sci-Fi      |            7 |
| CROWDS TELEMARK             | Sci-Fi      |            4 |
| DAISY MENAGERIE             | Sci-Fi      |            7 |
| DISTURBING SCARFACE         | Sci-Fi      |            4 |
| DIVIDE MONSTER              | Sci-Fi      |            6 |
| DOLLS RAGE                  | Sci-Fi      |            1 |
| ENGLISH BULWORTH            | Sci-Fi      |            5 |
| EXPRESS LONELY              | Sci-Fi      |            8 |
| EYES DRIVING                | Sci-Fi      |            5 |
| FIDDLER LOST                | Sci-Fi      |           11 |
| FISH OPUS                   | Sci-Fi      |            2 |
| FRISCO FORREST              | Sci-Fi      |            9 |
| GARDEN ISLAND               | Sci-Fi      |            3 |
| GOLDMINE TYCOON             | Sci-Fi      |            7 |
| GOODFELLAS SALUTE           | Sci-Fi      |            8 |
| GRAFFITI LOVE               | Sci-Fi      |            6 |
| GUYS FALCON                 | Sci-Fi      |            5 |
| HAMLET WISDOM               | Sci-Fi      |            5 |
| HANKY OCTOBER               | Sci-Fi      |            3 |
| HOLLOW JEOPARDY             | Sci-Fi      |            2 |
| IDENTITY LOVER              | Sci-Fi      |            4 |
| LICENSE WEEKEND             | Sci-Fi      |            8 |
| MARRIED GO                  | Sci-Fi      |            3 |
| METROPOLIS COMA             | Sci-Fi      |            6 |
| MOURNING PURPLE             | Sci-Fi      |            7 |
| NEMO CAMPUS                 | Sci-Fi      |            5 |
| NONE SPIKING                | Sci-Fi      |            6 |
| OPEN AFRICAN                | Sci-Fi      |            9 |
| PANTHER REDS                | Sci-Fi      |            5 |
| RAGING AIRPLANE             | Sci-Fi      |            3 |
| RANDOM GO                   | Sci-Fi      |           13 |
| REIGN GENTLEMEN             | Sci-Fi      |            3 |
| SILVERADO GOLDFINGER        | Sci-Fi      |            5 |
| SOLDIERS EVOLUTION          | Sci-Fi      |            9 |
| SPIRITED CASUALTIES         | Sci-Fi      |            5 |
| STALLION SUNDANCE           | Sci-Fi      |            7 |
| SUICIDES SILENCE            | Sci-Fi      |            3 |
| SUN CONFESSIONS             | Sci-Fi      |            5 |
| TITANS JERK                 | Sci-Fi      |            7 |
| TROJAN TOMORROW             | Sci-Fi      |            8 |
| UNFORGIVEN ZOOLANDER        | Sci-Fi      |            7 |
| VACATION BOONDOCK           | Sci-Fi      |            6 |
| WEEKEND PERSONAL            | Sci-Fi      |           10 |
| WHISPERER GIANT             | Sci-Fi      |            3 |
| WONDERLAND CHRISTMAS        | Sci-Fi      |            5 |
| ALADDIN CALENDAR            | Sports      |            8 |
| ANONYMOUS HUMAN             | Sports      |            9 |
| ARTIST COLDBLOODED          | Sports      |            7 |
| BUBBLE GROSSE               | Sports      |            3 |
| CALIFORNIA BIRDS            | Sports      |            2 |
| CARIBBEAN LIBERTY           | Sports      |            8 |
| CHANCE RESURRECTION         | Sports      |            6 |
| CONGENIALITY QUEST          | Sports      |            3 |
| CRANES RESERVOIR            | Sports      |            6 |
| CRUSADE HONEY               | Sports      |            9 |
| DIVORCE SHINING             | Sports      |            6 |
| DRIVER ANNIE                | Sports      |            8 |
| DROP WATERFRONT             | Sports      |            8 |
| DUDE BLINDNESS              | Sports      |            7 |
| DURHAM PANKY                | Sports      |            9 |
| ELIZABETH SHANE             | Sports      |            3 |
| EVOLUTION ALTER             | Sports      |            6 |
| EXORCIST STING              | Sports      |            5 |
| FLATLINERS KILLER           | Sports      |            9 |
| GLEAMING JAWBREAKER         | Sports      |            8 |
| GRACELAND DYNAMITE          | Sports      |            6 |
| GROOVE FICTION              | Sports      |            7 |
| GUNFIGHTER MUSSOLINI        | Sports      |            4 |
| HOLES BRANNIGAN             | Sports      |           11 |
| HONEY TIES                  | Sports      |            5 |
| HYSTERICAL GRAIL            | Sports      |            9 |
| IMAGE PRINCESS              | Sports      |           11 |
| INSTINCT AIRPORT            | Sports      |           11 |
| JADE BUNCH                  | Sports      |            8 |
| JOON NORTHWEST              | Sports      |            2 |
| KRAMER CHOCOLATE            | Sports      |            8 |
| LESSON CLEOPATRA            | Sports      |           12 |
| LIBERTY MAGNIFICENT         | Sports      |            7 |
| LOSER HUSTLER               | Sports      |            5 |
| MERMAID INSECTS             | Sports      |            6 |
| MILE MULAN                  | Sports      |            3 |
| MOSQUITO ARMAGEDDON         | Sports      |            4 |
| MOTHER OLEANDER             | Sports      |            5 |
| MUMMY CREATURES             | Sports      |           13 |
| MUSSOLINI SPOILERS          | Sports      |            7 |
| NEIGHBORS CHARADE           | Sports      |            7 |
| NORTHWEST POLISH            | Sports      |            8 |
| NOVOCAINE FLIGHT            | Sports      |            6 |
| PEACH INNOCENT              | Sports      |            5 |
| PEAK FOREVER                | Sports      |            5 |
| PERDITION FARGO             | Sports      |            5 |
| PHILADELPHIA WIFE           | Sports      |            2 |
| PICKUP DRIVING              | Sports      |            5 |
| PIRATES ROXANNE             | Sports      |            1 |
| POSEIDON FOREVER            | Sports      |            6 |
| RECORDS ZORRO               | Sports      |            8 |
| RIDER CADDYSHACK            | Sports      |            9 |
| RIVER OUTLAW                | Sports      |            4 |
| ROSES TREASURE              | Sports      |            5 |
| SATISFACTION CONFIDENTIAL   | Sports      |            5 |
| SATURDAY LAMBS              | Sports      |            9 |
| SEABISCUIT PUNK             | Sports      |            3 |
| SECRETARY ROUGE             | Sports      |            6 |
| SENSE GREEK                 | Sports      |            7 |
| SHAKESPEARE SADDLE          | Sports      |            6 |
| SIERRA DIVIDE               | Sports      |            5 |
| SLIPPER FIDELITY            | Sports      |            7 |
| SMOOCHY CONTROL             | Sports      |            2 |
| SQUAD FISH                  | Sports      |            5 |
| STAR OPERATION              | Sports      |            5 |
| STEERS ARMAGEDDON           | Sports      |            4 |
| STRAIGHT HOURS              | Sports      |            3 |
| TALENTED HOMICIDE           | Sports      |            5 |
| TIGHTS DAWN                 | Sports      |            5 |
| TOURIST PELICAN             | Sports      |            3 |
| TRADING PINOCCHIO           | Sports      |            3 |
| TUXEDO MILE                 | Sports      |            3 |
| VICTORY ACADEMY             | Sports      |            5 |
| ARSENIC INDEPENDENCE        | Travel      |            3 |
| BASIC EASY                  | Travel      |            6 |
| BIRD INDEPENDENCE           | Travel      |            2 |
| BOILED DARES                | Travel      |            8 |
| BOONDOCK BALLROOM           | Travel      |           13 |
| BORN SPINAL                 | Travel      |            9 |
| BUCKET BROTHERHOOD          | Travel      |            6 |
| CASABLANCA SUPER            | Travel      |            4 |
| CASSIDY WYOMING             | Travel      |            7 |
| COMA HEAD                   | Travel      |            3 |
| COMFORTS RUSH               | Travel      |            5 |
| CONTACT ANONYMOUS           | Travel      |            5 |
| DESPERATE TRAINSPOTTING     | Travel      |            4 |
| DISCIPLE MOTHER             | Travel      |            7 |
| ENOUGH RAGING               | Travel      |            9 |
| ESCAPE METROPOLIS           | Travel      |            4 |
| EXPECATIONS NATURAL         | Travel      |            3 |
| FACTORY DRAGON              | Travel      |            6 |
| FELLOWSHIP AUTUMN           | Travel      |            7 |
| FROGMEN BREAKING            | Travel      |            6 |
| FUGITIVE MAGUIRE            | Travel      |           11 |
| GAMES BOWFINGER             | Travel      |            8 |
| GUMP DATE                   | Travel      |            6 |
| HAUNTED ANTITRUST           | Travel      |            5 |
| HORROR REIGN                | Travel      |            5 |
| IGBY MAKER                  | Travel      |            5 |
| ITALIAN AFRICAN             | Travel      |            2 |
| KICK SAVANNAH               | Travel      |            6 |
| LEATHERNECKS DWARFS         | Travel      |            7 |
| LIAISONS SWEET              | Travel      |            6 |
| LOCK REAR                   | Travel      |            2 |
| MADIGAN DORADO              | Travel      |            6 |
| MOULIN WAKE                 | Travel      |            3 |
| MUSCLE BRIGHT               | Travel      |            5 |
| ORDER BETRAYED              | Travel      |            7 |
| OTHERS SOUP                 | Travel      |            4 |
| OUTLAW HANKY                | Travel      |            7 |
| PAPI NECKLACE               | Travel      |            3 |
| SHANE DARKNESS              | Travel      |            3 |
| SHANGHAI TYCOON             | Travel      |            8 |
| SHAWSHANK BUBBLE            | Travel      |           10 |
| SHINING ROSES               | Travel      |            5 |
| SMILE EARRING               | Travel      |            8 |
| SPEED SUIT                  | Travel      |            6 |
| STONE FIRE                  | Travel      |            1 |
| SUPERFLY TRIP               | Travel      |            7 |
| SWEET BROTHERHOOD           | Travel      |            6 |
| TEEN APOLLO                 | Travel      |            5 |
| TOMATOES HELLFIGHTERS       | Travel      |            9 |
| TRAFFIC HOBBIT              | Travel      |            4 |
| TROUBLE DATE                | Travel      |            8 |
| VALENTINE VANISHING         | Travel      |            2 |
| WINDOW SIDE                 | Travel      |            4 |
| WOLVES DESIRE               | Travel      |            6 |
| WORKER TARZAN               | Travel      |            9 |
| WORKING MICROCOSMOS         | Travel      |            5 |
+-----------------------------+-------------+--------------+

