CREATE VIEW popular_movies_by_category AS
select c.name AS category, f.title, COUNT(*) AS total_rentals
from film_category fc
join film as f ON fc.film_id = f.film_id
join category as c ON fc.category_id = c.category_id
join inventory as i ON f.film_id = i.film_id
join rental as r ON i.inventory_id = r.inventory_id
group by c.name, f.title
order by total_rentals DESC;

+-------------+-----------------------------+---------------+
| category    | title                       | total_rentals |
+-------------+-----------------------------+---------------+
| Travel      | BUCKET BROTHERHOOD          |            34 |
| Foreign     | ROCKETEER MOTHER            |            33 |
| Animation   | JUGGLER HARDLY              |            32 |
| Games       | FORWARD TEMPLE              |            32 |
| Games       | GRIT CLOCKWORK              |            32 |
| Music       | SCALAWAG DUCK               |            32 |
| New         | RIDGEMONT SUBMARINE         |            32 |
| Children    | ROBBERS JOON                |            31 |
| Classics    | TIMBERLAND SKY              |            31 |
| Comedy      | ZORRO ARK                   |            31 |
| Documentary | WIFE TURN                   |            31 |
| Drama       | HOBBIT ALIEN                |            31 |
| Family      | APACHE DIVINE               |            31 |
| Family      | NETWORK PEAK                |            31 |
| Family      | RUSH GOODFELLAS             |            31 |
| Sci-Fi      | GOODFELLAS SALUTE           |            31 |
| Action      | RUGRATS SHAKESPEARE         |            30 |
| Action      | SUSPECTS QUILLS             |            30 |
| Animation   | DOGMA FAMILY                |            30 |
| Children    | IDOLS SNATCHERS             |            30 |
| Classics    | FROST HEAD                  |            30 |
| Comedy      | CAT CONEHEADS               |            30 |
| Drama       | HARRY IDAHO                 |            30 |
| Drama       | WITCHES PANIC               |            30 |
| Foreign     | SHOCK CABIN                 |            30 |
| Games       | MASSACRE USUAL              |            30 |
| Horror      | PULP BEVERLY                |            30 |
| New         | BUTTERFLY CHOCOLAT          |            30 |
| Sci-Fi      | ENGLISH BULWORTH            |            30 |
| Sci-Fi      | GRAFFITI LOVE               |            30 |
| Sci-Fi      | MARRIED GO                  |            30 |
| Travel      | MUSCLE BRIGHT               |            30 |
| Animation   | STORM HAPPINESS             |            29 |
| Children    | SWEETHEARTS SUSPECTS        |            29 |
| Documentary | VIRGINIAN PLUTO             |            29 |
| Foreign     | MOON BUNCH                  |            29 |
| Games       | VIDEOTAPE ARSENIC           |            29 |
| Horror      | FAMILY SWEET                |            29 |
| Music       | BOOGIE AMELIE               |            29 |
| Music       | CONFIDENTIAL INTERVIEW      |            29 |
| Music       | DEER VIRGINIAN              |            29 |
| Music       | ENEMY ODDS                  |            29 |
| Music       | GREATEST NORTH              |            29 |
| Sci-Fi      | BINGO TALENTED              |            29 |
| Sci-Fi      | TITANS JERK                 |            29 |
| Sports      | GLEAMING JAWBREAKER         |            29 |
| Sports      | TALENTED HOMICIDE           |            29 |
| Action      | HANDICAP BOONDOCK           |            28 |
| Action      | STORY SIDE                  |            28 |
| Action      | TRIP NEWTON                 |            28 |
| Children    | GIANT TROOPERS              |            28 |
| Classics    | GILMORE BOILED              |            28 |
| Classics    | VOYAGE LEGALLY              |            28 |
| Comedy      | CLOSER BANG                 |            28 |
| Documentary | EXPENDABLE STALLION         |            28 |
| New         | FATAL HAUNTED               |            28 |
| Sports      | ROSES TREASURE              |            28 |
| Sports      | SATURDAY LAMBS              |            28 |
| Action      | PRIMARY GLASS               |            27 |
| Animation   | BLACKOUT PRIVATE            |            27 |
| Animation   | FORRESTER COMANCHEROS       |            27 |
| Animation   | GANGS PRIDE                 |            27 |
| Children    | INVASION CYCLONE            |            27 |
| Classics    | DETECTIVE VISION            |            27 |
| Classics    | LOATHING LEGALLY            |            27 |
| Comedy      | OPERATION OPERATION         |            27 |
| Documentary | DANCING FEVER               |            27 |
| Documentary | PRINCESS GIANT              |            27 |
| Drama       | LIES TREATMENT              |            27 |
| Drama       | TORQUE BOUND                |            27 |
| Drama       | WARDROBE PHANTOM            |            27 |
| Family      | MOVIE SHAKESPEARE           |            27 |
| Family      | RANGE MOONWALKER            |            27 |
| Foreign     | LOSE INCH                   |            27 |
| Games       | CURTAIN VIDEOTAPE           |            27 |
| Games       | SPY MILE                    |            27 |
| Horror      | SWARM GOLD                  |            27 |
| Music       | DORADO NOTTING              |            27 |
| Music       | TELEGRAPH VOYAGE            |            27 |
| Sci-Fi      | CAMELOT VACATION            |            27 |
| Sci-Fi      | GOLDMINE TYCOON             |            27 |
| Sci-Fi      | NONE SPIKING                |            27 |
| Sports      | CHANCE RESURRECTION         |            27 |
| Travel      | HORROR REIGN                |            27 |
| Action      | FANTASY TROOPERS            |            26 |
| Action      | STAGECOACH ARMAGEDDON       |            26 |
| Animation   | TRACY CIDER                 |            26 |
| Classics    | HYDE DOCTOR                 |            26 |
| Classics    | ISLAND EXORCIST             |            26 |
| Classics    | MALKOVICH PET               |            26 |
| Classics    | WESTWARD SEABISCUIT         |            26 |
| Comedy      | VELVET TERMINATOR           |            26 |
| Documentary | BROTHERHOOD BLANKET         |            26 |
| Documentary | PELICAN COMFORTS            |            26 |
| Documentary | POCUS PULP                  |            26 |
| Drama       | PITY BOUND                  |            26 |
| Family      | HALF OUTFIELD               |            26 |
| Foreign     | INNOCENT USUAL              |            26 |
| Music       | ALASKA PHANTOM              |            26 |
| Sci-Fi      | DISTURBING SCARFACE         |            26 |
| Sci-Fi      | HANKY OCTOBER               |            26 |
| Sci-Fi      | METROPOLIS COMA             |            26 |
| Sports      | DURHAM PANKY                |            26 |
| Sports      | SEABISCUIT PUNK             |            26 |
| Sports      | TIGHTS DAWN                 |            26 |
| Travel      | COMA HEAD                   |            26 |
| Travel      | CONTACT ANONYMOUS           |            26 |
| Travel      | FELLOWSHIP AUTUMN           |            26 |
| Action      | CLUELESS BUCKET             |            25 |
| Action      | HILLS NEIGHBORS             |            25 |
| Animation   | CLASH FREDDY                |            25 |
| Animation   | DOUBLE WRATH                |            25 |
| Animation   | OSCAR GOLD                  |            25 |
| Animation   | TELEMARK HEARTBREAKERS      |            25 |
| Children    | SHEPHERD MIDSUMMER          |            25 |
| Classics    | DYNAMITE TARZAN             |            25 |
| Classics    | TOMORROW HUSTLER            |            25 |
| Comedy      | DOWNHILL ENOUGH             |            25 |
| Comedy      | MALLRATS UNITED             |            25 |
| Documentary | METAL ARMAGEDDON            |            25 |
| Documentary | SHOW LORD                   |            25 |
| Drama       | CONEHEADS SMOOCHY           |            25 |
| Family      | EFFECT GLADIATOR            |            25 |
| Family      | FEUD FROGMEN                |            25 |
| Foreign     | MADNESS ATTACKS             |            25 |
| Games       | GUN BONNIE                  |            25 |
| Games       | NIGHTMARE CHILL             |            25 |
| Horror      | STREETCAR INTENTIONS        |            25 |
| New         | SAMURAI LION                |            25 |
| Sci-Fi      | BARBARELLA STREETCAR        |            25 |
| Sci-Fi      | FISH OPUS                   |            25 |
| Sci-Fi      | SUN CONFESSIONS             |            25 |
| Sports      | TRADING PINOCCHIO           |            25 |
| Travel      | ESCAPE METROPOLIS           |            25 |
| Travel      | WORKING MICROCOSMOS         |            25 |
| Action      | CELEBRITY HORN              |            24 |
| Action      | DRIFTER COMMANDMENTS        |            24 |
| Action      | MOCKINGBIRD HOLLYWOOD       |            24 |
| Animation   | HORN WORKING                |            24 |
| Animation   | OZ LIAISONS                 |            24 |
| Animation   | SUNRISE LEAGUE              |            24 |
| Children    | FARGO GANDHI                |            24 |
| Children    | JUMPING WRATH               |            24 |
| Children    | STRANGELOVE DESIRE          |            24 |
| Classics    | BOUND CHEAPER               |            24 |
| Classics    | CENTER DINOSAUR             |            24 |
| Classics    | COLOR PHILADELPHIA          |            24 |
| Comedy      | CAPER MOTIONS               |            24 |
| Comedy      | GUNFIGHT MOON               |            24 |
| Comedy      | HURRICANE AFFAIR            |            24 |
| Comedy      | KNOCK WARLOCK               |            24 |
| Documentary | PACIFIC AMISTAD             |            24 |
| Documentary | WEDDING APOLLO              |            24 |
| Drama       | GOLDFINGER SENSIBILITY      |            24 |
| Drama       | SEATTLE EXPECATIONS         |            24 |
| Drama       | SHOOTIST SUPERFLY           |            24 |
| Family      | ATLANTIS CAUSE              |            24 |
| Family      | JASON TRAP                  |            24 |
| Family      | SLUMS DUCK                  |            24 |
| Foreign     | ALAMO VIDEOTAPE             |            24 |
| Foreign     | ORANGE GRAPES               |            24 |
| Games       | ICE CROSSING                |            24 |
| Horror      | ARACHNOPHOBIA ROLLERCOASTER |            24 |
| Horror      | LOLA AGENT                  |            24 |
| Horror      | SLEEPING SUSPECTS           |            24 |
| Music       | ROMAN PUNK                  |            24 |
| New         | ATTRACTION NEWTON           |            24 |
| New         | MAIDEN HOME                 |            24 |
| Action      | EASY GLADIATOR              |            23 |
| Action      | FOOL MOCKINGBIRD            |            23 |
| Action      | TRUMAN CRAZY                |            23 |
| Action      | WOMEN DORADO                |            23 |
| Animation   | SNOWMAN ROLLERCOASTER       |            23 |
| Animation   | TITANIC BOONDOCK            |            23 |
| Children    | CROOKED FROGMEN             |            23 |
| Children    | MURDER ANTITRUST            |            23 |
| Classics    | STEEL SANTA                 |            23 |
| Comedy      | STRICTLY SCARFACE           |            23 |
| Documentary | ACADEMY DINOSAUR            |            23 |
| Documentary | CUPBOARD SINNERS            |            23 |
| Documentary | HEAVYWEIGHTS BEAST          |            23 |
| Drama       | KWAI HOMEWARD               |            23 |
| Drama       | SCORPION APOLLO             |            23 |
| Family      | HOUSE DYNAMITE              |            23 |
| Foreign     | GENTLEMEN STAGE             |            23 |
| Foreign     | WASH HEAVENLY               |            23 |
| Games       | CANDLES GRAPES              |            23 |
| Games       | NAME DETECTIVE              |            23 |
| Games       | OUTBREAK DIVINE             |            23 |
| Games       | WIND PHANTOM                |            23 |
| Horror      | AFFAIR PREJUDICE            |            23 |
| Horror      | CARRIE BUNCH                |            23 |
| Horror      | FREDDY STORM                |            23 |
| Horror      | KARATE MOON                 |            23 |
| Horror      | PATTON INTERVIEW            |            23 |
| Horror      | YENTL IDAHO                 |            23 |
| Music       | BALLOON HOMEWARD            |            23 |
| New         | EARTH VISION                |            23 |
| New         | FLAMINGOS CONNECTICUT       |            23 |
| New         | SALUTE APOLLO               |            23 |
| Sports      | ALADDIN CALENDAR            |            23 |
| Sports      | PHILADELPHIA WIFE           |            23 |
| Travel      | OTHERS SOUP                 |            23 |
| Travel      | TROUBLE DATE                |            23 |
| Action      | AMERICAN CIRCUS             |            22 |
| Action      | DREAM PICKUP                |            22 |
| Action      | SOUTH WAIT                  |            22 |
| Animation   | ALTER VICTORY               |            22 |
| Animation   | BORROWERS BEDAZZLED         |            22 |
| Animation   | FALCON VOLUME               |            22 |
| Animation   | FIGHT JAWBREAKER            |            22 |
| Animation   | PACKER MADIGAN              |            22 |
| Children    | BEAR GRACELAND              |            22 |
| Comedy      | HUSTLER PARTY               |            22 |
| Comedy      | SNATCH SLIPPER              |            22 |
| Documentary | CHICKEN HELLFIGHTERS        |            22 |
| Documentary | MIDSUMMER GROUNDHOG         |            22 |
| Drama       | BEAUTY GREASE               |            22 |
| Drama       | BLADE POLISH                |            22 |
| Drama       | CHILL LUCK                  |            22 |
| Drama       | QUEEN LUKE                  |            22 |
| Drama       | SEA VIRGIN                  |            22 |
| Family      | HOMICIDE PEACH              |            22 |
| Foreign     | ALIEN CENTER                |            22 |
| Foreign     | GRAPES FURY                 |            22 |
| Foreign     | KISS GLORY                  |            22 |
| Games       | HAUNTING PIANIST            |            22 |
| Games       | HEAD STRANGER               |            22 |
| Games       | MALTESE HOPE                |            22 |
| Games       | VOLCANO TEXAS               |            22 |
| Horror      | HIGH ENCINO                 |            22 |
| Horror      | SINNERS ATLANTIS            |            22 |
| Music       | BANGER PINOCCHIO            |            22 |
| New         | ANGELS LIFE                 |            22 |
| New         | EAGLES PANKY                |            22 |
| Sci-Fi      | ANNIE IDENTITY              |            22 |
| Sci-Fi      | WHISPERER GIANT             |            22 |
| Sci-Fi      | WONDERLAND CHRISTMAS        |            22 |
| Sports      | CONGENIALITY QUEST          |            22 |
| Sports      | FLATLINERS KILLER           |            22 |
| Sports      | SHAKESPEARE SADDLE          |            22 |
| Sports      | TOURIST PELICAN             |            22 |
| Travel      | LIAISONS SWEET              |            22 |
| Action      | AMADEUS HOLY                |            21 |
| Action      | BERETS AGENT                |            21 |
| Action      | EXCITEMENT EVE              |            21 |
| Animation   | ANACONDA CONFESSIONS        |            21 |
| Animation   | CROSSROADS CASUALTIES       |            21 |
| Animation   | WAIT CIDER                  |            21 |
| Children    | CHRISTMAS MOONSHINE         |            21 |
| Children    | EMPIRE MALKOVICH            |            21 |
| Children    | GHOST GROUNDHOG             |            21 |
| Children    | SABRINA MIDNIGHT            |            21 |
| Children    | SPLENDOR PATTON             |            21 |
| Classics    | ARIZONA BANG                |            21 |
| Classics    | DRACULA CRYSTAL             |            21 |
| Comedy      | DOOM DANCING                |            21 |
| Comedy      | FIREBALL PHILADELPHIA       |            21 |
| Documentary | CAUSE DATE                  |            21 |
| Documentary | COAST RAINBOW               |            21 |
| Documentary | EGG IGBY                    |            21 |
| Documentary | SECRET GROUNDHOG            |            21 |
| Drama       | DECEIVER BETRAYED           |            21 |
| Drama       | LEBOWSKI SOLDIERS           |            21 |
| Family      | BLUES INSTINCT              |            21 |
| Family      | GREASE YOUTH                |            21 |
| Family      | RESURRECTION SILVERADO      |            21 |
| Foreign     | AGENT TRUMAN                |            21 |
| Foreign     | BROOKLYN DESERT             |            21 |
| Foreign     | CALENDAR GUNFIGHT           |            21 |
| Foreign     | HIGHBALL POTTER             |            21 |
| Games       | MOONSHINE CABIN             |            21 |
| Games       | SLEUTH ORIENT               |            21 |
| Games       | SUIT WALLS                  |            21 |
| Horror      | FIDELITY DEVIL              |            21 |
| Horror      | UNDEFEATED DALMATIONS       |            21 |
| Music       | DRIVING POLISH              |            21 |
| New         | AMISTAD MIDSUMMER           |            21 |
| New         | PIANIST OUTFIELD            |            21 |
| New         | SLEEPY JAPANESE             |            21 |
| New         | STING PERSONAL              |            21 |
| New         | UNBREAKABLE KARATE          |            21 |
| Sci-Fi      | ARMAGEDDON LOST             |            21 |
| Sci-Fi      | BADMAN DAWN                 |            21 |
| Sci-Fi      | BEVERLY OUTLAW              |            21 |
| Sci-Fi      | CHAINSAW UPTOWN             |            21 |
| Sci-Fi      | CHARIOTS CONSPIRACY         |            21 |
| Sci-Fi      | DIVIDE MONSTER              |            21 |
| Sci-Fi      | MOURNING PURPLE             |            21 |
| Sci-Fi      | OPEN AFRICAN                |            21 |
| Sci-Fi      | VACATION BOONDOCK           |            21 |
| Sports      | PIRATES ROXANNE             |            21 |
| Sports      | STAR OPERATION              |            21 |
| Travel      | BASIC EASY                  |            21 |
| Travel      | WOLVES DESIRE               |            21 |
| Action      | KISSING DOLLS               |            20 |
| Action      | MINDS TRUMAN                |            20 |
| Action      | QUEST MUSSOLINI             |            20 |
| Animation   | FLYING HOOK                 |            20 |
| Animation   | HARPER DYING                |            20 |
| Animation   | ROOM ROMAN                  |            20 |
| Animation   | SLEEPLESS MONSOON           |            20 |
| Children    | HEARTBREAKERS BRIGHT        |            20 |
| Children    | WRONG BEHAVIOR              |            20 |
| Classics    | JERK PAYCHECK               |            20 |
| Classics    | MILLION ACE                 |            20 |
| Classics    | PREJUDICE OLEANDER          |            20 |
| Comedy      | BRINGING HYSTERICAL         |            20 |
| Comedy      | PINOCCHIO SIMON             |            20 |
| Comedy      | TRAMP OTHERS                |            20 |
| Drama       | DALMATIONS SWEDEN           |            20 |
| Drama       | HUNCHBACK IMPOSSIBLE        |            20 |
| Drama       | REUNION WITCHES             |            20 |
| Drama       | SPICE SORORITY              |            20 |
| Family      | CHASING FIGHT               |            20 |
| Family      | CHOCOLAT HARRY              |            20 |
| Family      | DINOSAUR SECRETARY          |            20 |
| Family      | SECRETS PARADISE            |            20 |
| Foreign     | HELLFIGHTERS SIERRA         |            20 |
| Foreign     | INTRIGUE WORST              |            20 |
| Foreign     | JET NEIGHBORS               |            20 |
| Foreign     | STEPMOM DREAM               |            20 |
| Horror      | LOVE SUICIDES               |            20 |
| Music       | GO PURPLE                   |            20 |
| Music       | INSIDER ARIZONA             |            20 |
| Music       | MASKED BUBBLE               |            20 |
| Music       | OUTFIELD MASSACRE           |            20 |
| New         | INTERVIEW LIAISONS          |            20 |
| New         | MONEY HAROLD                |            20 |
| New         | REDEMPTION COMFORTS         |            20 |
| Sci-Fi      | CHEAPER CLYDE               |            20 |
| Sci-Fi      | GARDEN ISLAND               |            20 |
| Sci-Fi      | REIGN GENTLEMEN             |            20 |
| Sports      | NORTHWEST POLISH            |            20 |
| Sports      | PEAK FOREVER                |            20 |
| Sports      | RIVER OUTLAW                |            20 |
| Sports      | STRAIGHT HOURS              |            20 |
| Travel      | KICK SAVANNAH               |            20 |
| Action      | BRIDE INTRIGUE              |            19 |
| Action      | CAMPUS REMEMBER             |            19 |
| Animation   | CANYON STOCK                |            19 |
| Animation   | CLUB GRAFFITI               |            19 |
| Animation   | DOORS PRESIDENT             |            19 |
| Animation   | POND SEATTLE                |            19 |
| Animation   | THIEF PELICAN               |            19 |
| Children    | BACKLASH UNDEFEATED         |            19 |
| Children    | FURY MURDER                 |            19 |
| Children    | GORGEOUS BINGO              |            19 |
| Children    | SUNDANCE INVASION           |            19 |
| Classics    | PATIENT SISTER              |            19 |
| Classics    | REQUIEM TYCOON              |            19 |
| Documentary | BILL OTHERS                 |            19 |
| Documentary | CIDER DESIRE                |            19 |
| Documentary | INDEPENDENCE HOTEL          |            19 |
| Documentary | NATIONAL STORY              |            19 |
| Documentary | ROAD ROXANNE                |            19 |
| Drama       | ENCOUNTERS CURTAIN          |            19 |
| Drama       | HANGING DEEP                |            19 |
| Drama       | SOMETHING DUCK              |            19 |
| Family      | EARRING INSTINCT            |            19 |
| Family      | GABLES METROPOLIS           |            19 |
| Family      | JEDI BENEATH                |            19 |
| Family      | MUSIC BOONDOCK              |            19 |
| Family      | RAGE GAMES                  |            19 |
| Foreign     | FICTION CHRISTMAS           |            19 |
| Games       | DETAILS PACKER              |            19 |
| Games       | ENCINO ELF                  |            19 |
| Games       | FANTASIA PARK               |            19 |
| Games       | MARS ROMAN                  |            19 |
| Games       | ROXANNE REBEL               |            19 |
| Horror      | DESERT POSEIDON             |            19 |
| Music       | CLONES PINOCCHIO            |            19 |
| New         | HOURS RAGE                  |            19 |
| New         | MINE TITANS                 |            19 |
| New         | VOICE PEACH                 |            19 |
| Sci-Fi      | EYES DRIVING                |            19 |
| Sci-Fi      | TROJAN TOMORROW             |            19 |
| Sports      | HONEY TIES                  |            19 |
| Sports      | NEIGHBORS CHARADE           |            19 |
| Sports      | NOVOCAINE FLIGHT            |            19 |
| Travel      | DISCIPLE MOTHER             |            19 |
| Travel      | IGBY MAKER                  |            19 |
| Travel      | SHAWSHANK BUBBLE            |            19 |
| Action      | BAREFOOT MANCHURIAN         |            18 |
| Action      | DARN FORRESTER              |            18 |
| Action      | FORREST SONS                |            18 |
| Animation   | CAROL TEXAS                 |            18 |
| Animation   | INCH JET                    |            18 |
| Animation   | INSECTS STONE               |            18 |
| Animation   | MISSION ZOOLANDER           |            18 |
| Animation   | WONKA SEA                   |            18 |
| Children    | POLISH BROOKLYN             |            18 |
| Children    | SCARFACE BANG               |            18 |
| Classics    | CANDIDATE PERDITION         |            18 |
| Classics    | CORE SUIT                   |            18 |
| Classics    | GALAXY SWEETHEARTS          |            18 |
| Classics    | HOPE TOOTSIE                |            18 |
| Comedy      | GROUNDHOG UNCUT             |            18 |
| Comedy      | HEAVEN FREEDOM              |            18 |
| Comedy      | LION UNCUT                  |            18 |
| Comedy      | PARADISE SABRINA            |            18 |
| Comedy      | SWEDEN SHINING              |            18 |
| Documentary | SMOKING BARBARELLA          |            18 |
| Drama       | JACKET FRISCO               |            18 |
| Drama       | RACER EGG                   |            18 |
| Family      | REMEMBER DIARY              |            18 |
| Foreign     | POLLOCK DELIVERANCE         |            18 |
| Foreign     | WHALE BIKINI                |            18 |
| Games       | DAWN POND                   |            18 |
| Games       | ROUGE SQUAD                 |            18 |
| Horror      | AIRPORT POLLOCK             |            18 |
| Music       | ALONE TRIP                  |            18 |
| Music       | VANISHING ROCKY             |            18 |
| New         | BIRDS PERDITION             |            18 |
| New         | BOULEVARD MOB               |            18 |
| New         | CLEOPATRA DEVIL             |            18 |
| New         | DRAGONFLY STRANGERS         |            18 |
| Sci-Fi      | UNFORGIVEN ZOOLANDER        |            18 |
| Sci-Fi      | WEEKEND PERSONAL            |            18 |
| Sports      | DRIVER ANNIE                |            18 |
| Sports      | GROOVE FICTION              |            18 |
| Sports      | INSTINCT AIRPORT            |            18 |
| Sports      | JADE BUNCH                  |            18 |
| Sports      | SECRETARY ROUGE             |            18 |
| Travel      | ENOUGH RAGING               |            18 |
| Travel      | EXPECATIONS NATURAL         |            18 |
| Action      | MIDNIGHT WESTWARD           |            17 |
| Action      | REAR TRADING                |            17 |
| Action      | WATERFRONT DELIVERANCE      |            17 |
| Animation   | BIKINI BORROWERS            |            17 |
| Animation   | INTENTIONS EMPIRE           |            17 |
| Animation   | LAWLESS VISION              |            17 |
| Animation   | POTTER CONNECTICUT          |            17 |
| Animation   | SUGAR WONKA                 |            17 |
| Children    | HOLOCAUST HIGHBALL          |            17 |
| Children    | NOON PAPI                   |            17 |
| Children    | ZOOLANDER FICTION           |            17 |
| Classics    | LEAGUE HELLFIGHTERS         |            17 |
| Classics    | MUSKETEERS WAIT             |            17 |
| Classics    | ROOTS REMEMBER              |            17 |
| Comedy      | DYING MAKER                 |            17 |
| Comedy      | FERRIS MOTHER               |            17 |
| Comedy      | FLINTSTONES HAPPINESS       |            17 |
| Comedy      | PERFECT GROOVE              |            17 |
| Documentary | BEACH HEARTBREAKERS         |            17 |
| Documentary | FRENCH HOLIDAY              |            17 |
| Documentary | MAJESTIC FLOATS             |            17 |
| Documentary | UNITED PILOT                |            17 |
| Drama       | ORIENT CLOSER               |            17 |
| Drama       | SLACKER LIAISONS            |            17 |
| Drama       | VIRGIN DAISY                |            17 |
| Family      | CONFUSED CANDLES            |            17 |
| Family      | CONVERSATION DOWNHILL       |            17 |
| Family      | GANDHI KWAI                 |            17 |
| Family      | LOUISIANA HARRY             |            17 |
| Foreign     | GREEK EVERYONE              |            17 |
| Foreign     | NEWTON LABYRINTH            |            17 |
| Games       | JERICHO MULAN               |            17 |
| Horror      | EGYPT TENENBAUMS            |            17 |
| Horror      | LADY STAGE                  |            17 |
| Horror      | ROCK INSTINCT               |            17 |
| Horror      | STRANGERS GRAFFITI          |            17 |
| Music       | FREAKY POCUS                |            17 |
| Music       | HANOVER GALAXY              |            17 |
| Music       | TAXI KICK                   |            17 |
| New         | BREAKFAST GOLDFINGER        |            17 |
| New         | IDAHO LOVE                  |            17 |
| New         | JEKYLL FROGMEN              |            17 |
| New         | MASK PEACH                  |            17 |
| Sports      | JOON NORTHWEST              |            17 |
| Sports      | POSEIDON FOREVER            |            17 |
| Sports      | SATISFACTION CONFIDENTIAL   |            17 |
| Travel      | COMFORTS RUSH               |            17 |
| Travel      | FACTORY DRAGON              |            17 |
| Travel      | TEEN APOLLO                 |            17 |
| Action      | BULL SHAWSHANK              |            16 |
| Action      | CADDYSHACK JEDI             |            16 |
| Action      | PATRIOT ROMAN               |            16 |
| Action      | UPRISING UPTOWN             |            16 |
| Action      | WORST BANGER                |            16 |
| Animation   | PRIDE ALAMO                 |            16 |
| Animation   | WATCH TRACY                 |            16 |
| Children    | GRADUATE LORD               |            16 |
| Children    | HALL CASSIDY                |            16 |
| Classics    | JEEPERS WEDDING             |            16 |
| Classics    | SUMMER SCARFACE             |            16 |
| Comedy      | PURE RUNNER                 |            16 |
| Documentary | ARMY FLINTSTONES            |            16 |
| Documentary | BONNIE HOLOCAUST            |            16 |
| Documentary | HOMEWARD CIDER              |            16 |
| Documentary | QUILLS BULL                 |            16 |
| Documentary | SAGEBRUSH CLUELESS          |            16 |
| Documentary | STREAK RIDGEMONT            |            16 |
| Drama       | CONQUERER NUTS              |            16 |
| Drama       | CRAFT OUTFIELD              |            16 |
| Drama       | PAYCHECK WAIT               |            16 |
| Drama       | ROCKY WAR                   |            16 |
| Drama       | WEST LION                   |            16 |
| Family      | BAKED CLEOPATRA             |            16 |
| Family      | INDIAN LOVE                 |            16 |
| Family      | PILOT HOOSIERS              |            16 |
| Family      | WILLOW TRACY                |            16 |
| Foreign     | COMMAND DARLING             |            16 |
| Foreign     | TRAP GUYS                   |            16 |
| Games       | CHICAGO NORTH               |            16 |
| Games       | CREATURES SHAKESPEARE       |            16 |
| Games       | WANDA CHAMBER               |            16 |
| Horror      | GASLIGHT CRUSADE            |            16 |
| Horror      | MOTIONS DETAILS             |            16 |
| Horror      | REAP UNFAITHFUL             |            16 |
| Horror      | RULES HUMAN                 |            16 |
| Music       | SILENCE KANE                |            16 |
| Music       | WIZARD COLDBLOODED          |            16 |
| Music       | WORDS HUNTER                |            16 |
| New         | DESTINY SATURDAY            |            16 |
| New         | PLUTO OLEANDER              |            16 |
| New         | VARSITY TRIP                |            16 |
| Sci-Fi      | ATTACKS HATE                |            16 |
| Sci-Fi      | COLDBLOODED DARLING         |            16 |
| Sci-Fi      | DAISY MENAGERIE             |            16 |
| Sports      | ARTIST COLDBLOODED          |            16 |
| Sports      | DUDE BLINDNESS              |            16 |
| Sports      | MERMAID INSECTS             |            16 |
| Sports      | MUMMY CREATURES             |            16 |
| Sports      | PICKUP DRIVING              |            16 |
| Sports      | SLIPPER FIDELITY            |            16 |
| Travel      | CASABLANCA SUPER            |            16 |
| Travel      | LOCK REAR                   |            16 |
| Travel      | MOULIN WAKE                 |            16 |
| Action      | DEVIL DESIRE                |            15 |
| Action      | ENTRAPMENT SATISFACTION     |            15 |
| Action      | LUST LOCK                   |            15 |
| Action      | RINGS HEARTBREAKERS         |            15 |
| Animation   | NASH CHOCOLAT               |            15 |
| Animation   | SONS INTERVIEW              |            15 |
| Children    | BETRAYED REAR               |            15 |
| Children    | CABIN FLASH                 |            15 |
| Children    | CIRCUS YOUTH                |            15 |
| Children    | LABYRINTH LEAGUE            |            15 |
| Children    | MODEL FISH                  |            15 |
| Children    | TOOTSIE PILOT               |            15 |
| Classics    | WASTELAND DIVINE            |            15 |
| Comedy      | AIRPLANE SIERRA             |            15 |
| Comedy      | ANTHEM LUKE                 |            15 |
| Comedy      | LONELY ELEPHANT             |            15 |
| Comedy      | SUBMARINE BED               |            15 |
| Comedy      | VALLEY PACKER               |            15 |
| Documentary | MADISON TRAP                |            15 |
| Documentary | MODERN DORADO               |            15 |
| Documentary | SHIP WONDERLAND             |            15 |
| Drama       | EDGE KISSING                |            15 |
| Drama       | NECKLACE OUTBREAK           |            15 |
| Drama       | TRANSLATION SUMMER          |            15 |
| Drama       | VIETNAM SMOOCHY             |            15 |
| Family      | HUNTING MUSKETEERS          |            15 |
| Family      | MANCHURIAN CURTAIN          |            15 |
| Family      | ODDS BOOGIE                 |            15 |
| Family      | SIEGE MADRE                 |            15 |
| Foreign     | CYCLONE FAMILY              |            15 |
| Foreign     | HOLIDAY GAMES               |            15 |
| Foreign     | ILLUSION AMELIE             |            15 |
| Foreign     | SCISSORHANDS SLUMS          |            15 |
| Foreign     | SHREK LICENSE               |            15 |
| Games       | DIRTY ACE                   |            15 |
| Games       | DIVINE RESURRECTION         |            15 |
| Games       | HUMAN GRAFFITI              |            15 |
| Games       | PANKY SUBMARINE             |            15 |
| Horror      | SPIRIT FLINTSTONES          |            15 |
| Music       | MONSTER SPARTACUS           |            15 |
| Sci-Fi      | CHARADE DUFFEL              |            15 |
| Sci-Fi      | PANTHER REDS                |            15 |
| Sports      | HOLES BRANNIGAN             |            15 |
| Sports      | HYSTERICAL GRAIL            |            15 |
| Sports      | LOSER HUSTLER               |            15 |
| Sports      | MOSQUITO ARMAGEDDON         |            15 |
| Sports      | SIERRA DIVIDE               |            15 |
| Sports      | STEERS ARMAGEDDON           |            15 |
| Travel      | BOILED DARES                |            15 |
| Travel      | SWEET BROTHERHOOD           |            15 |
| Travel      | WORKER TARZAN               |            15 |
| Action      | DANCES NONE                 |            14 |
| Action      | GLASS DYING                 |            14 |
| Action      | SHRUNK DIVINE               |            14 |
| Action      | WEREWOLF LOLA               |            14 |
| Animation   | DONNIE ALLEY                |            14 |
| Animation   | TURN STAR                   |            14 |
| Classics    | CREEPERS KANE               |            14 |
| Classics    | LOVELY JINGLE               |            14 |
| Classics    | PAJAMA JAWBREAKER           |            14 |
| Comedy      | GOLD RIVER                  |            14 |
| Comedy      | JAWS HARRY                  |            14 |
| Comedy      | SADDLE ANTITRUST            |            14 |
| Comedy      | SEARCHERS WAIT              |            14 |
| Documentary | DEEP CRUSADE                |            14 |
| Documentary | NOTORIOUS REUNION           |            14 |
| Documentary | WRATH MILE                  |            14 |
| Drama       | CONFESSIONS MAGUIRE         |            14 |
| Drama       | GREEDY ROOTS                |            14 |
| Family      | SPLASH GUMP                 |            14 |
| Family      | VIRTUAL SPOILERS            |            14 |
| Foreign     | ALLEY EVOLUTION             |            14 |
| Foreign     | IMPOSSIBLE PREJUDICE        |            14 |
| Foreign     | KANE EXORCIST               |            14 |
| Foreign     | TOWN ARK                    |            14 |
| Games       | GRINCH MASSAGE              |            14 |
| Games       | MADRE GABLES                |            14 |
| Games       | STAMPEDE DISTURBING         |            14 |
| Horror      | ANALYZE HOOSIERS            |            14 |
| Horror      | ELEPHANT TROJAN             |            14 |
| Horror      | PARIS WEEKEND               |            14 |
| Music       | HOME PITY                   |            14 |
| Music       | PERSONAL LADYBUGS           |            14 |
| Music       | UNCUT SUICIDES              |            14 |
| New         | DAY UNFAITHFUL              |            14 |
| New         | STOCK GLASS                 |            14 |
| New         | TROOPERS METAL              |            14 |
| Sci-Fi      | BLINDNESS GUN               |            14 |
| Sci-Fi      | HAMLET WISDOM               |            14 |
| Sci-Fi      | NEMO CAMPUS                 |            14 |
| Sports      | IMAGE PRINCESS              |            14 |
| Sports      | MOTHER OLEANDER             |            14 |
| Sports      | PEACH INNOCENT              |            14 |
| Travel      | GAMES BOWFINGER             |            14 |
| Travel      | OUTLAW HANKY                |            14 |
| Travel      | SHANE DARKNESS              |            14 |
| Travel      | SHANGHAI TYCOON             |            14 |
| Travel      | TOMATOES HELLFIGHTERS       |            14 |
| Action      | LAWRENCE LOVE               |            13 |
| Animation   | CHAMPION FLATLINERS         |            13 |
| Animation   | HOOK CHARIOTS               |            13 |
| Children    | FOREVER CANDIDATE           |            13 |
| Children    | HOLLYWOOD ANONYMOUS         |            13 |
| Children    | MICROCOSMOS PARADISE        |            13 |
| Classics    | JINGLE SAGEBRUSH            |            13 |
| Classics    | SPIKING ELEMENT             |            13 |
| Comedy      | DADDY PITTSBURGH            |            13 |
| Comedy      | MEMENTO ZOOLANDER           |            13 |
| Comedy      | MULAN MOON                  |            13 |
| Comedy      | PARTY KNOCK                 |            13 |
| Comedy      | SATURN NAME                 |            13 |
| Drama       | BRIGHT ENCOUNTERS           |            13 |
| Drama       | DARKNESS WAR                |            13 |
| Drama       | TENENBAUMS COMMAND          |            13 |
| Family      | BEDAZZLED MARRIED           |            13 |
| Family      | BILKO ANONYMOUS             |            13 |
| Family      | CHISUM BEHAVIOR             |            13 |
| Family      | DATE SPEED                  |            13 |
| Family      | NATURAL STOCK               |            13 |
| Family      | OPPOSITE NECKLACE           |            13 |
| Family      | ROBBERY BRIGHT              |            13 |
| Family      | SPINAL ROCKY                |            13 |
| Family      | SUPER WYOMING               |            13 |
| Foreign     | EVERYONE CRAFT              |            13 |
| Foreign     | HUNGER ROOF                 |            13 |
| Foreign     | PAST SUICIDES               |            13 |
| Foreign     | PURPLE MOVIE                |            13 |
| Foreign     | USUAL UNTOUCHABLES          |            13 |
| Games       | MOONWALKER FOOL             |            13 |
| Games       | SASSY PACKER                |            13 |
| Games       | STATE WASTELAND             |            13 |
| Horror      | ARABIA DOGMA                |            13 |
| Horror      | BEHAVIOR RUNAWAY            |            13 |
| Horror      | DRUMS DYNAMITE              |            13 |
| Horror      | MONTEREY LABYRINTH          |            13 |
| Music       | CHAMBER ITALIAN             |            13 |
| Music       | LUCKY FLYING                |            13 |
| New         | BREAKING HOME               |            13 |
| New         | FLASH WARS                  |            13 |
| New         | WYOMING STORM               |            13 |
| Sci-Fi      | CINCINATTI WHISPERER        |            13 |
| Sci-Fi      | CITIZEN SHREK               |            13 |
| Sci-Fi      | CONNECTICUT TRAMP           |            13 |
| Sci-Fi      | EXPRESS LONELY              |            13 |
| Sci-Fi      | IDENTITY LOVER              |            13 |
| Sci-Fi      | RAGING AIRPLANE             |            13 |
| Sports      | ANONYMOUS HUMAN             |            13 |
| Sports      | EXORCIST STING              |            13 |
| Sports      | MILE MULAN                  |            13 |
| Sports      | TUXEDO MILE                 |            13 |
| Action      | CROW GREASE                 |            12 |
| Action      | SIDE ARK                    |            12 |
| Action      | SPEAKEASY DATE              |            12 |
| Animation   | MASSAGE IMAGE               |            12 |
| Children    | UPTOWN YOUNG                |            12 |
| Comedy      | HEDWIG ALTER                |            12 |
| Documentary | ADAPTATION HOLES            |            12 |
| Documentary | MIGHTY LUCK                 |            12 |
| Drama       | MOB DUFFEL                  |            12 |
| Drama       | SAVANNAH TOWN               |            12 |
| Family      | AFRICAN EGG                 |            12 |
| Family      | BLANKET BEVERLY             |            12 |
| Family      | FINDING ANACONDA            |            12 |
| Family      | PITTSBURGH HUNCHBACK        |            12 |
| Foreign     | DANGEROUS UPTOWN            |            12 |
| Foreign     | LOST BIRD                   |            12 |
| Foreign     | MEET CHOCOLATE              |            12 |
| Foreign     | SORORITY QUEEN              |            12 |
| Foreign     | WAR NOTTING                 |            12 |
| Games       | TYCOON GATHERING            |            12 |
| Horror      | ALABAMA DEVIL               |            12 |
| Horror      | TEMPLE ATTRACTION           |            12 |
| Music       | MINORITY KISS               |            12 |
| New         | BRANNIGAN SUNRISE           |            12 |
| New         | LOVERBOY ATTACKS            |            12 |
| New         | VAMPIRE WHALE               |            12 |
| Sci-Fi      | SILVERADO GOLDFINGER        |            12 |
| Sports      | CALIFORNIA BIRDS            |            12 |
| Sports      | EVOLUTION ALTER             |            12 |
| Sports      | FLIGHT LIES                 |            12 |
| Sports      | GUNFIGHTER MUSSOLINI        |            12 |
| Sports      | LIBERTY MAGNIFICENT         |            12 |
| Sports      | SMOOCHY CONTROL             |            12 |
| Travel      | BORN SPINAL                 |            12 |
| Travel      | VALENTINE VANISHING         |            12 |
| Travel      | WINDOW SIDE                 |            12 |
| Action      | DARKO DORADO                |            11 |
| Action      | DRAGON SQUAD                |            11 |
| Action      | LORD ARIZONA                |            11 |
| Action      | MAGNOLIA FORRESTER          |            11 |
| Animation   | POTLUCK MIXED               |            11 |
| Animation   | THEORY MERMAID              |            11 |
| Children    | LANGUAGE COWBOY             |            11 |
| Children    | SANTA PARIS                 |            11 |
| Children    | STRANGER STRANGERS          |            11 |
| Children    | TIES HUNGER                 |            11 |
| Children    | TWISTED PIRATES             |            11 |
| Classics    | BEAST HUNCHBACK             |            11 |
| Classics    | IRON MOON                   |            11 |
| Classics    | OCTOBER SUBMARINE           |            11 |
| Classics    | TOWERS HURRICANE            |            11 |
| Comedy      | TRAINSPOTTING STRANGERS     |            11 |
| Documentary | MOD SECRETARY               |            11 |
| Documentary | NORTH TEQUILA               |            11 |
| Documentary | THIN SAGEBRUSH              |            11 |
| Drama       | BEETHOVEN EXORCIST          |            11 |
| Family      | PRIX UNDEFEATED             |            11 |
| Foreign     | BUGSY SONG                  |            11 |
| Foreign     | FRIDA SLIPPER               |            11 |
| Foreign     | OPUS ICE                    |            11 |
| Games       | AUTUMN CROW                 |            11 |
| Games       | FEATHERS METAL              |            11 |
| Games       | GATHERING CALENDAR          |            11 |
| Horror      | BOWFINGER GABLES            |            11 |
| Horror      | REEF SALUTE                 |            11 |
| Music       | BIRCH ANTITRUST             |            11 |
| Music       | SONG HEDWIG                 |            11 |
| New         | ENDING CROWDS               |            11 |
| Sci-Fi      | SPIRITED CASUALTIES         |            11 |
| Sports      | CRANES RESERVOIR            |            11 |
| Sports      | RIDER CADDYSHACK            |            11 |
| Travel      | BIRD INDEPENDENCE           |            11 |
| Travel      | DRUMLINE CYCLONE            |            11 |
| Travel      | FUGITIVE MAGUIRE            |            11 |
| Travel      | STONE FIRE                  |            11 |
| Action      | ANTITRUST TOMATOES          |            10 |
| Action      | GRAIL FRANKENSTEIN          |            10 |
| Children    | BENEATH RUSH                |            10 |
| Children    | CLOCKWORK PARADISE          |            10 |
| Children    | MAKER GABLES                |            10 |
| Classics    | JEOPARDY ENCINO             |            10 |
| Classics    | LOVER TRUMAN                |            10 |
| Classics    | RIGHT CRANES                |            10 |
| Comedy      | ELEMENT FREDDY              |            10 |
| Comedy      | LIFE TWISTED                |            10 |
| Comedy      | MYSTIC TRUMAN               |            10 |
| Comedy      | STAGE WORLD                 |            10 |
| Documentary | HALLOWEEN NUTS              |            10 |
| Documentary | SPOILERS HELLFIGHTERS       |            10 |
| Documentary | WAGON JAWS                  |            10 |
| Documentary | WARS PLUTO                  |            10 |
| Drama       | GONE TROUBLE                |            10 |
| Drama       | LUCK OPUS                   |            10 |
| Drama       | NOTTING SPEAKEASY           |            10 |
| Drama       | PATHS CONTROL               |            10 |
| Family      | BLOOD ARGONAUTS             |            10 |
| Family      | LOLITA WORLD                |            10 |
| Family      | SENSIBILITY REAR            |            10 |
| Foreign     | DOUBTFIRE LABYRINTH         |            10 |
| Foreign     | RESERVOIR ADAPTATION        |            10 |
| Games       | LAMBS CINCINATTI            |            10 |
| Horror      | ROLLERCOASTER BRINGING      |            10 |
| Music       | AMELIE HELLFIGHTERS         |            10 |
| Music       | JAWBREAKER BROOKLYN         |            10 |
| Music       | OLEANDER CLUE               |            10 |
| New         | RUN PACIFIC                 |            10 |
| Sci-Fi      | FIDDLER LOST                |            10 |
| Sci-Fi      | HOLLOW JEOPARDY             |            10 |
| Sports      | ELIZABETH SHANE             |            10 |
| Travel      | FROGMEN BREAKING            |            10 |
| Travel      | MADIGAN DORADO              |            10 |
| Travel      | SMILE EARRING               |            10 |
| Travel      | SUPERFLY TRIP               |            10 |
| Action      | CASUALTIES ENCINO           |             9 |
| Action      | MONTEZUMA COMMAND           |             9 |
| Animation   | DARES PLUTO                 |             9 |
| Animation   | GHOSTBUSTERS ELF            |             9 |
| Animation   | MIRACLE VIRTUAL             |             9 |
| Children    | DAUGHTER MADIGAN            |             9 |
| Children    | LEGALLY SECRETARY           |             9 |
| Classics    | GILBERT PELICAN             |             9 |
| Classics    | HOLY TADPOLE                |             9 |
| Classics    | SNATCHERS MONTEZUMA         |             9 |
| Comedy      | CRAZY HOME                  |             9 |
| Comedy      | WISDOM WORKER               |             9 |
| Documentary | INTOLERABLE INTENTIONS      |             9 |
| Drama       | DIARY PANIC                 |             9 |
| Family      | KING EVOLUTION              |             9 |
| Family      | MAGUIRE APACHE              |             9 |
| Family      | SPARTACUS CHEAPER           |             9 |
| Foreign     | HOTEL HAPPINESS             |             9 |
| Foreign     | MATRIX SNOWMAN              |             9 |
| Foreign     | WONDERFUL DROP              |             9 |
| Games       | DARLING BREAKING            |             9 |
| Games       | DWARFS ALTER                |             9 |
| Games       | MONSOON CAUSE               |             9 |
| Games       | VANILLA DAY                 |             9 |
| Horror      | ALI FOREVER                 |             9 |
| Horror      | ANYTHING SAVANNAH           |             9 |
| Horror      | ZHIVAGO CORE                |             9 |
| Music       | BIRDCAGE CASPER             |             9 |
| Music       | IMPACT ALADDIN              |             9 |
| Music       | LEGEND JEDI                 |             9 |
| Music       | REDS POCUS                  |             9 |
| Music       | WON DARES                   |             9 |
| New         | JUNGLE CLOSER               |             9 |
| New         | NUTS TIES                   |             9 |
| New         | PLATOON INSTINCT            |             9 |
| Sci-Fi      | DOLLS RAGE                  |             9 |
| Sci-Fi      | FRISCO FORREST              |             9 |
| Sci-Fi      | GUYS FALCON                 |             9 |
| Sci-Fi      | RANDOM GO                   |             9 |
| Sports      | CARIBBEAN LIBERTY           |             9 |
| Sports      | DROP WATERFRONT             |             9 |
| Sports      | KRAMER CHOCOLATE            |             9 |
| Sports      | VICTORY ACADEMY             |             9 |
| Travel      | SPEED SUIT                  |             9 |
| Action      | GOSFORD DONNIE              |             8 |
| Action      | PARK CITIZEN                |             8 |
| Animation   | DESIRE ALIEN                |             8 |
| Animation   | PUNK DIVORCE                |             8 |
| Children    | CASPER DRAGONFLY            |             8 |
| Classics    | LIGHTS DEER                 |             8 |
| Classics    | MAGNIFICENT CHITTY          |             8 |
| Comedy      | VERTIGO NORTHWEST           |             8 |
| Documentary | UNTOUCHABLES SUNRISE        |             8 |
| Drama       | CHITTY LOCK                 |             8 |
| Drama       | DESTINATION JERK            |             8 |
| Drama       | HAROLD FRENCH               |             8 |
| Drama       | SAINTS BRIDE                |             8 |
| Drama       | UNFAITHFUL KILL             |             8 |
| Family      | SOUP WISDOM                 |             8 |
| Family      | SUNSET RACER                |             8 |
| Foreign     | BABY HALL                   |             8 |
| Foreign     | BALLROOM MOCKINGBIRD        |             8 |
| Foreign     | HOOSIERS BIRDCAGE           |             8 |
| Foreign     | MAUDE MOD                   |             8 |
| Foreign     | PET HAUNTING                |             8 |
| Horror      | TARZAN VIDEOTAPE            |             8 |
| Horror      | WORLD LEATHERNECKS          |             8 |
| Music       | GROSSE WONDERFUL            |             8 |
| Music       | REBEL AIRPORT               |             8 |
| Music       | RUNNER MADIGAN              |             8 |
| New         | CHAPLIN LICENSE             |             8 |
| New         | CLYDE THEORY                |             8 |
| New         | GODFATHER DIARY             |             8 |
| New         | JUMANJI BLADE               |             8 |
| New         | RUNAWAY TENENBAUMS          |             8 |
| Sci-Fi      | SOLDIERS EVOLUTION          |             8 |
| Sports      | CRUSADE HONEY               |             8 |
| Sports      | RECORDS ZORRO               |             8 |
| Travel      | PAPI NECKLACE               |             8 |
| Travel      | SHINING ROSES               |             8 |
| Animation   | EARLY HOME                  |             7 |
| Animation   | ISHTAR ROCKETEER            |             7 |
| Animation   | LUKE MUMMY                  |             7 |
| Animation   | MENAGERIE RUSHMORE          |             7 |
| Children    | DOCTOR GRAIL                |             7 |
| Children    | MAGIC MALLRATS              |             7 |
| Classics    | CRUELTY UNFORGIVEN          |             7 |
| Comedy      | CONNECTION MICROCOSMOS      |             7 |
| Comedy      | CONTROL ANTHEM              |             7 |
| Documentary | CLERKS ANGELS               |             7 |
| Documentary | DOZEN LION                  |             7 |
| Documentary | DUFFEL APOCALYPSE           |             7 |
| Documentary | HAWK CHILL                  |             7 |
| Documentary | NEWSIES STORY               |             7 |
| Documentary | YOUNG LANGUAGE              |             7 |
| Drama       | TREATMENT JEKYLL            |             7 |
| Family      | BANG KWAI                   |             7 |
| Family      | PRESIDENT BANG              |             7 |
| Foreign     | COWBOY DOOM                 |             7 |
| Foreign     | MULHOLLAND BEAST            |             7 |
| Foreign     | VISION TORQUE               |             7 |
| Games       | BULWORTH COMMANDMENTS       |             7 |
| Games       | FIRE WOLVES                 |             7 |
| Games       | PIZZA JUMANJI               |             7 |
| Horror      | ACE GOLDFINGER              |             7 |
| Horror      | PANIC CLUB                  |             7 |
| Music       | CLUE GRAIL                  |             7 |
| Music       | ELF MURDER                  |             7 |
| Music       | HEAVENLY GUN                |             7 |
| New         | EVE RESURRECTION            |             7 |
| New         | VANISHED GARDEN             |             7 |
| Sci-Fi      | LICENSE WEEKEND             |             7 |
| Sci-Fi      | STALLION SUNDANCE           |             7 |
| Sports      | DIVORCE SHINING             |             7 |
| Sports      | LESSON CLEOPATRA            |             7 |
| Sports      | SENSE GREEK                 |             7 |
| Sports      | SQUAD FISH                  |             7 |
| Travel      | LEATHERNECKS DWARFS         |             7 |
| Animation   | DUCK RACER                  |             6 |
| Children    | COMANCHEROS ENEMY           |             6 |
| Children    | JERSEY SASSY                |             6 |
| Children    | TEQUILA PAST                |             6 |
| Children    | WARLOCK WEREWOLF            |             6 |
| Classics    | EXTRAORDINARY CONQUERER     |             6 |
| Classics    | SLING LUKE                  |             6 |
| Comedy      | RUSHMORE MERMAID            |             6 |
| Documentary | BED HIGHBALL                |             6 |
| Family      | DUMBO LUST                  |             6 |
| Family      | KILLER INNOCENT             |             6 |
| Foreign     | HAPPINESS UNITED            |             6 |
| Foreign     | SCHOOL JACKET               |             6 |
| Games       | LADYBUGS ARMAGEDDON         |             6 |
| Horror      | JAPANESE RUN                |             6 |
| Horror      | SIMON NORTH                 |             6 |
| Horror      | TEXAS WATCH                 |             6 |
| Horror      | WATERSHIP FRONTIER          |             6 |
| Music       | TERMINATOR CLUB             |             6 |
| Music       | YOUTH KICK                  |             6 |
| New         | APOCALYPSE FLAMINGOS        |             6 |
| New         | FRONTIER CABIN              |             6 |
| New         | OKLAHOMA JUMANJI            |             6 |
| New         | PHANTOM GLORY               |             6 |
| New         | WILD APOLLO                 |             6 |
| Sports      | BUBBLE GROSSE               |             6 |
| Sports      | GRACELAND DYNAMITE          |             6 |
| Travel      | CASSIDY WYOMING             |             6 |
| Travel      | DESPERATE TRAINSPOTTING     |             6 |
| Travel      | HAUNTED ANTITRUST           |             6 |
| Travel      | ITALIAN AFRICAN             |             6 |
| Children    | FULL FLATLINERS             |             5 |
| Classics    | CONSPIRACY SPIRIT           |             5 |
| Comedy      | FREEDOM CLEOPATRA           |             5 |
| Documentary | HUNTER ALTER                |             5 |
| Drama       | BUNCH MINDS                 |             5 |
| Family      | BRAVEHEART HUMAN            |             5 |
| Foreign     | INFORMER DOUBLE             |             5 |
| Games       | FEVER EMPIRE                |             5 |
| Games       | GLORY TRACY                 |             5 |
| Games       | PRIVATE DROP                |             5 |
| Games       | SEVEN SWARM                 |             5 |
| New         | MANNEQUIN WORST             |             5 |
| Sports      | MUSSOLINI SPOILERS          |             5 |
| Travel      | TRAFFIC HOBBIT              |             5 |
| Documentary | HARDLY ROBBERS              |             4 |
| Foreign     | MIXED DOORS                 |             4 |
| Horror      | TRAIN BUNCH                 |             4 |
+-------------+-----------------------------+---------------+

